// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: constants.proto
// Protobuf Java Version: 4.36.1

package focstim_rpc;

@com.google.protobuf.Generated
public final class Constants extends com.google.protobuf.GeneratedFile {
  private Constants() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "Constants");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code focstim_rpc.AxisType}
   */
  public enum AxisType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AXIS_UNKNOWN = 0;</code>
     */
    AXIS_UNKNOWN(0),
    /**
     * <pre>
     * position parameters
     * </pre>
     *
     * <code>AXIS_POSITION_ALPHA = 1;</code>
     */
    AXIS_POSITION_ALPHA(1),
    /**
     * <code>AXIS_POSITION_BETA = 2;</code>
     */
    AXIS_POSITION_BETA(2),
    /**
     * <code>AXIS_POSITION_GAMMA = 3;</code>
     */
    AXIS_POSITION_GAMMA(3),
    /**
     * <pre>
     * AXIS_VOLUME_PERCENT = 10;    // not used
     * </pre>
     *
     * <code>AXIS_WAVEFORM_AMPLITUDE_AMPS = 11;</code>
     */
    AXIS_WAVEFORM_AMPLITUDE_AMPS(11),
    /**
     * <pre>
     * general pulse parameters
     * </pre>
     *
     * <code>AXIS_CARRIER_FREQUENCY_HZ = 20;</code>
     */
    AXIS_CARRIER_FREQUENCY_HZ(20),
    /**
     * <code>AXIS_PULSE_WIDTH_IN_CYCLES = 21;</code>
     */
    AXIS_PULSE_WIDTH_IN_CYCLES(21),
    /**
     * <code>AXIS_PULSE_RISE_TIME_CYCLES = 22;</code>
     */
    AXIS_PULSE_RISE_TIME_CYCLES(22),
    /**
     * <code>AXIS_PULSE_FREQUENCY_HZ = 23;</code>
     */
    AXIS_PULSE_FREQUENCY_HZ(23),
    /**
     * <code>AXIS_PULSE_INTERVAL_RANDOM_PERCENT = 24;</code>
     */
    AXIS_PULSE_INTERVAL_RANDOM_PERCENT(24),
    /**
     * <code>AXIS_CALIBRATION_3_CENTER = 30;</code>
     */
    AXIS_CALIBRATION_3_CENTER(30),
    /**
     * <code>AXIS_CALIBRATION_3_UP = 31;</code>
     */
    AXIS_CALIBRATION_3_UP(31),
    /**
     * <code>AXIS_CALIBRATION_3_LEFT = 32;</code>
     */
    AXIS_CALIBRATION_3_LEFT(32),
    /**
     * <pre>
     * not used
     * </pre>
     *
     * <code>AXIS_CALIBRATION_4_CENTER = 40;</code>
     */
    AXIS_CALIBRATION_4_CENTER(40),
    /**
     * <code>AXIS_CALIBRATION_4_A = 41;</code>
     */
    AXIS_CALIBRATION_4_A(41),
    /**
     * <code>AXIS_CALIBRATION_4_B = 42;</code>
     */
    AXIS_CALIBRATION_4_B(42),
    /**
     * <code>AXIS_CALIBRATION_4_C = 43;</code>
     */
    AXIS_CALIBRATION_4_C(43),
    /**
     * <code>AXIS_CALIBRATION_4_D = 44;</code>
     */
    AXIS_CALIBRATION_4_D(44),
    /**
     * <code>AXIS_CALIBRATION_4_REDUCTION_IN_CENTER = 45;</code>
     */
    AXIS_CALIBRATION_4_REDUCTION_IN_CENTER(45),
    /**
     * <code>AXIS_ELECTRODE_1_POWER = 50;</code>
     */
    AXIS_ELECTRODE_1_POWER(50),
    /**
     * <code>AXIS_ELECTRODE_2_POWER = 51;</code>
     */
    AXIS_ELECTRODE_2_POWER(51),
    /**
     * <code>AXIS_ELECTRODE_3_POWER = 52;</code>
     */
    AXIS_ELECTRODE_3_POWER(52),
    /**
     * <code>AXIS_ELECTRODE_4_POWER = 53;</code>
     */
    AXIS_ELECTRODE_4_POWER(53),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "AxisType");
    }
    /**
     * <code>AXIS_UNKNOWN = 0;</code>
     */
    public static final int AXIS_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * position parameters
     * </pre>
     *
     * <code>AXIS_POSITION_ALPHA = 1;</code>
     */
    public static final int AXIS_POSITION_ALPHA_VALUE = 1;
    /**
     * <code>AXIS_POSITION_BETA = 2;</code>
     */
    public static final int AXIS_POSITION_BETA_VALUE = 2;
    /**
     * <code>AXIS_POSITION_GAMMA = 3;</code>
     */
    public static final int AXIS_POSITION_GAMMA_VALUE = 3;
    /**
     * <pre>
     * AXIS_VOLUME_PERCENT = 10;    // not used
     * </pre>
     *
     * <code>AXIS_WAVEFORM_AMPLITUDE_AMPS = 11;</code>
     */
    public static final int AXIS_WAVEFORM_AMPLITUDE_AMPS_VALUE = 11;
    /**
     * <pre>
     * general pulse parameters
     * </pre>
     *
     * <code>AXIS_CARRIER_FREQUENCY_HZ = 20;</code>
     */
    public static final int AXIS_CARRIER_FREQUENCY_HZ_VALUE = 20;
    /**
     * <code>AXIS_PULSE_WIDTH_IN_CYCLES = 21;</code>
     */
    public static final int AXIS_PULSE_WIDTH_IN_CYCLES_VALUE = 21;
    /**
     * <code>AXIS_PULSE_RISE_TIME_CYCLES = 22;</code>
     */
    public static final int AXIS_PULSE_RISE_TIME_CYCLES_VALUE = 22;
    /**
     * <code>AXIS_PULSE_FREQUENCY_HZ = 23;</code>
     */
    public static final int AXIS_PULSE_FREQUENCY_HZ_VALUE = 23;
    /**
     * <code>AXIS_PULSE_INTERVAL_RANDOM_PERCENT = 24;</code>
     */
    public static final int AXIS_PULSE_INTERVAL_RANDOM_PERCENT_VALUE = 24;
    /**
     * <code>AXIS_CALIBRATION_3_CENTER = 30;</code>
     */
    public static final int AXIS_CALIBRATION_3_CENTER_VALUE = 30;
    /**
     * <code>AXIS_CALIBRATION_3_UP = 31;</code>
     */
    public static final int AXIS_CALIBRATION_3_UP_VALUE = 31;
    /**
     * <code>AXIS_CALIBRATION_3_LEFT = 32;</code>
     */
    public static final int AXIS_CALIBRATION_3_LEFT_VALUE = 32;
    /**
     * <pre>
     * not used
     * </pre>
     *
     * <code>AXIS_CALIBRATION_4_CENTER = 40;</code>
     */
    public static final int AXIS_CALIBRATION_4_CENTER_VALUE = 40;
    /**
     * <code>AXIS_CALIBRATION_4_A = 41;</code>
     */
    public static final int AXIS_CALIBRATION_4_A_VALUE = 41;
    /**
     * <code>AXIS_CALIBRATION_4_B = 42;</code>
     */
    public static final int AXIS_CALIBRATION_4_B_VALUE = 42;
    /**
     * <code>AXIS_CALIBRATION_4_C = 43;</code>
     */
    public static final int AXIS_CALIBRATION_4_C_VALUE = 43;
    /**
     * <code>AXIS_CALIBRATION_4_D = 44;</code>
     */
    public static final int AXIS_CALIBRATION_4_D_VALUE = 44;
    /**
     * <code>AXIS_CALIBRATION_4_REDUCTION_IN_CENTER = 45;</code>
     */
    public static final int AXIS_CALIBRATION_4_REDUCTION_IN_CENTER_VALUE = 45;
    /**
     * <code>AXIS_ELECTRODE_1_POWER = 50;</code>
     */
    public static final int AXIS_ELECTRODE_1_POWER_VALUE = 50;
    /**
     * <code>AXIS_ELECTRODE_2_POWER = 51;</code>
     */
    public static final int AXIS_ELECTRODE_2_POWER_VALUE = 51;
    /**
     * <code>AXIS_ELECTRODE_3_POWER = 52;</code>
     */
    public static final int AXIS_ELECTRODE_3_POWER_VALUE = 52;
    /**
     * <code>AXIS_ELECTRODE_4_POWER = 53;</code>
     */
    public static final int AXIS_ELECTRODE_4_POWER_VALUE = 53;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AxisType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AxisType forNumber(int value) {
      switch (value) {
        case 0: return AXIS_UNKNOWN;
        case 1: return AXIS_POSITION_ALPHA;
        case 2: return AXIS_POSITION_BETA;
        case 3: return AXIS_POSITION_GAMMA;
        case 11: return AXIS_WAVEFORM_AMPLITUDE_AMPS;
        case 20: return AXIS_CARRIER_FREQUENCY_HZ;
        case 21: return AXIS_PULSE_WIDTH_IN_CYCLES;
        case 22: return AXIS_PULSE_RISE_TIME_CYCLES;
        case 23: return AXIS_PULSE_FREQUENCY_HZ;
        case 24: return AXIS_PULSE_INTERVAL_RANDOM_PERCENT;
        case 30: return AXIS_CALIBRATION_3_CENTER;
        case 31: return AXIS_CALIBRATION_3_UP;
        case 32: return AXIS_CALIBRATION_3_LEFT;
        case 40: return AXIS_CALIBRATION_4_CENTER;
        case 41: return AXIS_CALIBRATION_4_A;
        case 42: return AXIS_CALIBRATION_4_B;
        case 43: return AXIS_CALIBRATION_4_C;
        case 44: return AXIS_CALIBRATION_4_D;
        case 45: return AXIS_CALIBRATION_4_REDUCTION_IN_CENTER;
        case 50: return AXIS_ELECTRODE_1_POWER;
        case 51: return AXIS_ELECTRODE_2_POWER;
        case 52: return AXIS_ELECTRODE_3_POWER;
        case 53: return AXIS_ELECTRODE_4_POWER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AxisType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AxisType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AxisType>() {
            public AxisType findValueByNumber(int number) {
              return AxisType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(0);
    }

    private static final AxisType[] VALUES = values();

    public static AxisType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AxisType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.AxisType)
  }

  /**
   * Protobuf enum {@code focstim_rpc.BoardIdentifier}
   */
  public enum BoardIdentifier
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BOARD_UNKNOWN = 0;</code>
     */
    BOARD_UNKNOWN(0),
    /**
     * <pre>
     * AKA 'V1' or 'V2'
     * </pre>
     *
     * <code>BOARD_B_G431B_ESC1 = 1;</code>
     */
    BOARD_B_G431B_ESC1(1),
    /**
     * <pre>
     * also V3
     * </pre>
     *
     * <code>BOARD_FOCSTIM_V4 = 2;</code>
     */
    BOARD_FOCSTIM_V4(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "BoardIdentifier");
    }
    /**
     * <code>BOARD_UNKNOWN = 0;</code>
     */
    public static final int BOARD_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * AKA 'V1' or 'V2'
     * </pre>
     *
     * <code>BOARD_B_G431B_ESC1 = 1;</code>
     */
    public static final int BOARD_B_G431B_ESC1_VALUE = 1;
    /**
     * <pre>
     * also V3
     * </pre>
     *
     * <code>BOARD_FOCSTIM_V4 = 2;</code>
     */
    public static final int BOARD_FOCSTIM_V4_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BoardIdentifier valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BoardIdentifier forNumber(int value) {
      switch (value) {
        case 0: return BOARD_UNKNOWN;
        case 1: return BOARD_B_G431B_ESC1;
        case 2: return BOARD_FOCSTIM_V4;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BoardIdentifier>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BoardIdentifier> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BoardIdentifier>() {
            public BoardIdentifier findValueByNumber(int number) {
              return BoardIdentifier.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(1);
    }

    private static final BoardIdentifier[] VALUES = values();

    public static BoardIdentifier valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BoardIdentifier(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.BoardIdentifier)
  }

  /**
   * Protobuf enum {@code focstim_rpc.OutputMode}
   */
  public enum OutputMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OUTPUT_UNKNOWN = 0;</code>
     */
    OUTPUT_UNKNOWN(0),
    /**
     * <pre>
     * OUTPUT_OFF = 1;
     * </pre>
     *
     * <code>OUTPUT_THREEPHASE = 2;</code>
     */
    OUTPUT_THREEPHASE(2),
    /**
     * <pre>
     * alpha, beta, gamma. DEPRECATED
     * </pre>
     *
     * <code>OUTPUT_FOURPHASE = 3;</code>
     */
    OUTPUT_FOURPHASE(3),
    /**
     * <pre>
     * e1/e2/e3/e4
     * </pre>
     *
     * <code>OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES = 4;</code>
     */
    OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "OutputMode");
    }
    /**
     * <code>OUTPUT_UNKNOWN = 0;</code>
     */
    public static final int OUTPUT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * OUTPUT_OFF = 1;
     * </pre>
     *
     * <code>OUTPUT_THREEPHASE = 2;</code>
     */
    public static final int OUTPUT_THREEPHASE_VALUE = 2;
    /**
     * <pre>
     * alpha, beta, gamma. DEPRECATED
     * </pre>
     *
     * <code>OUTPUT_FOURPHASE = 3;</code>
     */
    public static final int OUTPUT_FOURPHASE_VALUE = 3;
    /**
     * <pre>
     * e1/e2/e3/e4
     * </pre>
     *
     * <code>OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES = 4;</code>
     */
    public static final int OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OutputMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OutputMode forNumber(int value) {
      switch (value) {
        case 0: return OUTPUT_UNKNOWN;
        case 2: return OUTPUT_THREEPHASE;
        case 3: return OUTPUT_FOURPHASE;
        case 4: return OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OutputMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OutputMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OutputMode>() {
            public OutputMode findValueByNumber(int number) {
              return OutputMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(2);
    }

    private static final OutputMode[] VALUES = values();

    public static OutputMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OutputMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.OutputMode)
  }

  /**
   * <pre>
   * TODO: implement
   * </pre>
   *
   * Protobuf enum {@code focstim_rpc.StreamingMode}
   */
  public enum StreamingMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STREAMING_UNKNOWN = 0;</code>
     */
    STREAMING_UNKNOWN(0),
    /**
     * <code>STREAMING_MOVETO = 1;</code>
     */
    STREAMING_MOVETO(1),
    /**
     * <code>STREAMING_BUFFERED = 2;</code>
     */
    STREAMING_BUFFERED(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "StreamingMode");
    }
    /**
     * <code>STREAMING_UNKNOWN = 0;</code>
     */
    public static final int STREAMING_UNKNOWN_VALUE = 0;
    /**
     * <code>STREAMING_MOVETO = 1;</code>
     */
    public static final int STREAMING_MOVETO_VALUE = 1;
    /**
     * <code>STREAMING_BUFFERED = 2;</code>
     */
    public static final int STREAMING_BUFFERED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StreamingMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StreamingMode forNumber(int value) {
      switch (value) {
        case 0: return STREAMING_UNKNOWN;
        case 1: return STREAMING_MOVETO;
        case 2: return STREAMING_BUFFERED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StreamingMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StreamingMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StreamingMode>() {
            public StreamingMode findValueByNumber(int number) {
              return StreamingMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(3);
    }

    private static final StreamingMode[] VALUES = values();

    public static StreamingMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StreamingMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.StreamingMode)
  }

  /**
   * Protobuf enum {@code focstim_rpc.Errors}
   */
  public enum Errors
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_UNKNOWN = 0;</code>
     */
    ERROR_UNKNOWN(0),
    /**
     * <code>ERROR_OUTPUT_NOT_SUPPORTED = 1;</code>
     */
    ERROR_OUTPUT_NOT_SUPPORTED(1),
    /**
     * <code>ERROR_UNKNOWN_REQUEST = 2;</code>
     */
    ERROR_UNKNOWN_REQUEST(2),
    /**
     * <code>ERROR_POWER_NOT_PRESENT = 3;</code>
     */
    ERROR_POWER_NOT_PRESENT(3),
    /**
     * <code>ERROR_ALREADY_PLAYING = 4;</code>
     */
    ERROR_ALREADY_PLAYING(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "Errors");
    }
    /**
     * <code>ERROR_UNKNOWN = 0;</code>
     */
    public static final int ERROR_UNKNOWN_VALUE = 0;
    /**
     * <code>ERROR_OUTPUT_NOT_SUPPORTED = 1;</code>
     */
    public static final int ERROR_OUTPUT_NOT_SUPPORTED_VALUE = 1;
    /**
     * <code>ERROR_UNKNOWN_REQUEST = 2;</code>
     */
    public static final int ERROR_UNKNOWN_REQUEST_VALUE = 2;
    /**
     * <code>ERROR_POWER_NOT_PRESENT = 3;</code>
     */
    public static final int ERROR_POWER_NOT_PRESENT_VALUE = 3;
    /**
     * <code>ERROR_ALREADY_PLAYING = 4;</code>
     */
    public static final int ERROR_ALREADY_PLAYING_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Errors valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Errors forNumber(int value) {
      switch (value) {
        case 0: return ERROR_UNKNOWN;
        case 1: return ERROR_OUTPUT_NOT_SUPPORTED;
        case 2: return ERROR_UNKNOWN_REQUEST;
        case 3: return ERROR_POWER_NOT_PRESENT;
        case 4: return ERROR_ALREADY_PLAYING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Errors>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Errors> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Errors>() {
            public Errors findValueByNumber(int number) {
              return Errors.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(4);
    }

    private static final Errors[] VALUES = values();

    public static Errors valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Errors(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.Errors)
  }

  /**
   * Protobuf enum {@code focstim_rpc.ButtonState}
   */
  public enum ButtonState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUTTON_UNKNOWN = 0;</code>
     */
    BUTTON_UNKNOWN(0),
    /**
     * <code>BUTTON_DOWN = 1;</code>
     */
    BUTTON_DOWN(1),
    /**
     * <code>BUTTON_UP = 2;</code>
     */
    BUTTON_UP(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "ButtonState");
    }
    /**
     * <code>BUTTON_UNKNOWN = 0;</code>
     */
    public static final int BUTTON_UNKNOWN_VALUE = 0;
    /**
     * <code>BUTTON_DOWN = 1;</code>
     */
    public static final int BUTTON_DOWN_VALUE = 1;
    /**
     * <code>BUTTON_UP = 2;</code>
     */
    public static final int BUTTON_UP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ButtonState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ButtonState forNumber(int value) {
      switch (value) {
        case 0: return BUTTON_UNKNOWN;
        case 1: return BUTTON_DOWN;
        case 2: return BUTTON_UP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ButtonState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ButtonState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ButtonState>() {
            public ButtonState findValueByNumber(int number) {
              return ButtonState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return focstim_rpc.Constants.getDescriptor().getEnumType(5);
    }

    private static final ButtonState[] VALUES = values();

    public static ButtonState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ButtonState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:focstim_rpc.ButtonState)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017constants.proto\022\013focstim_rpc*\247\005\n\010AxisT" +
      "ype\022\020\n\014AXIS_UNKNOWN\020\000\022\027\n\023AXIS_POSITION_A" +
      "LPHA\020\001\022\026\n\022AXIS_POSITION_BETA\020\002\022\027\n\023AXIS_P" +
      "OSITION_GAMMA\020\003\022 \n\034AXIS_WAVEFORM_AMPLITU" +
      "DE_AMPS\020\013\022\035\n\031AXIS_CARRIER_FREQUENCY_HZ\020\024" +
      "\022\036\n\032AXIS_PULSE_WIDTH_IN_CYCLES\020\025\022\037\n\033AXIS" +
      "_PULSE_RISE_TIME_CYCLES\020\026\022\033\n\027AXIS_PULSE_" +
      "FREQUENCY_HZ\020\027\022&\n\"AXIS_PULSE_INTERVAL_RA" +
      "NDOM_PERCENT\020\030\022\035\n\031AXIS_CALIBRATION_3_CEN" +
      "TER\020\036\022\031\n\025AXIS_CALIBRATION_3_UP\020\037\022\033\n\027AXIS" +
      "_CALIBRATION_3_LEFT\020 \022\035\n\031AXIS_CALIBRATIO" +
      "N_4_CENTER\020(\022\030\n\024AXIS_CALIBRATION_4_A\020)\022\030" +
      "\n\024AXIS_CALIBRATION_4_B\020*\022\030\n\024AXIS_CALIBRA" +
      "TION_4_C\020+\022\030\n\024AXIS_CALIBRATION_4_D\020,\022*\n&" +
      "AXIS_CALIBRATION_4_REDUCTION_IN_CENTER\020-" +
      "\022\032\n\026AXIS_ELECTRODE_1_POWER\0202\022\032\n\026AXIS_ELE" +
      "CTRODE_2_POWER\0203\022\032\n\026AXIS_ELECTRODE_3_POW" +
      "ER\0204\022\032\n\026AXIS_ELECTRODE_4_POWER\0205*R\n\017Boar" +
      "dIdentifier\022\021\n\rBOARD_UNKNOWN\020\000\022\026\n\022BOARD_" +
      "B_G431B_ESC1\020\001\022\024\n\020BOARD_FOCSTIM_V4\020\002*y\n\n" +
      "OutputMode\022\022\n\016OUTPUT_UNKNOWN\020\000\022\025\n\021OUTPUT" +
      "_THREEPHASE\020\002\022\024\n\020OUTPUT_FOURPHASE\020\003\022*\n&O" +
      "UTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES\020\004*" +
      "T\n\rStreamingMode\022\025\n\021STREAMING_UNKNOWN\020\000\022" +
      "\024\n\020STREAMING_MOVETO\020\001\022\026\n\022STREAMING_BUFFE" +
      "RED\020\002*\216\001\n\006Errors\022\021\n\rERROR_UNKNOWN\020\000\022\036\n\032E" +
      "RROR_OUTPUT_NOT_SUPPORTED\020\001\022\031\n\025ERROR_UNK" +
      "NOWN_REQUEST\020\002\022\033\n\027ERROR_POWER_NOT_PRESEN" +
      "T\020\003\022\031\n\025ERROR_ALREADY_PLAYING\020\004*A\n\013Button" +
      "State\022\022\n\016BUTTON_UNKNOWN\020\000\022\017\n\013BUTTON_DOWN" +
      "\020\001\022\r\n\tBUTTON_UP\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
