// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: focstim_rpc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeerror")
public inline fun error(block: focstim_rpc.ErrorKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Error =
  focstim_rpc.ErrorKt.Dsl._create(focstim_rpc.FocstimRpc.Error.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.Error`
 */
public object ErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.FocstimRpc.Error.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.FocstimRpc.Error.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.FocstimRpc.Error = _builder.build()

    /**
     * ```
     * string message = 2;
     * string data = 3;
     * ```
     *
     * `.focstim_rpc.Errors code = 1;`
     */
    public var code: focstim_rpc.Constants.Errors
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    public var codeValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodeValue")
        get() = _builder.codeValue
      @kotlin.jvm.JvmName("setCodeValue")
        set(value) {
        _builder.codeValue = value
      }
    /**
     * ```
     * string message = 2;
     * string data = 3;
     * ```
     *
     * `.focstim_rpc.Errors code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.FocstimRpc.Error.copy(block: `focstim_rpc`.ErrorKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Error =
  `focstim_rpc`.ErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

