// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializefirmwareVersion")
public inline fun firmwareVersion(block: focstim_rpc.FirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.FirmwareVersion =
  focstim_rpc.FirmwareVersionKt.Dsl._create(focstim_rpc.Messages.FirmwareVersion.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.FirmwareVersion`
 */
public object FirmwareVersionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.FirmwareVersion.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.FirmwareVersion.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.FirmwareVersion = _builder.build()

    /**
     * `uint32 major = 1;`
     */
    public var major: kotlin.Int
      @kotlin.jvm.JvmName("getMajor")
        get() = _builder.major
      @kotlin.jvm.JvmName("setMajor")
        set(value) {
        _builder.major = value
      }
    /**
     * `uint32 major = 1;`
     */
    public fun clearMajor() {
      _builder.clearMajor()
    }

    /**
     * `uint32 minor = 2;`
     */
    public var minor: kotlin.Int
      @kotlin.jvm.JvmName("getMinor")
        get() = _builder.minor
      @kotlin.jvm.JvmName("setMinor")
        set(value) {
        _builder.minor = value
      }
    /**
     * `uint32 minor = 2;`
     */
    public fun clearMinor() {
      _builder.clearMinor()
    }

    /**
     * `uint32 revision = 3;`
     */
    public var revision: kotlin.Int
      @kotlin.jvm.JvmName("getRevision")
        get() = _builder.revision
      @kotlin.jvm.JvmName("setRevision")
        set(value) {
        _builder.revision = value
      }
    /**
     * `uint32 revision = 3;`
     */
    public fun clearRevision() {
      _builder.clearRevision()
    }

    /**
     * `string branch = 4;`
     */
    public var branch: kotlin.String
      @kotlin.jvm.JvmName("getBranch")
        get() = _builder.branch
      @kotlin.jvm.JvmName("setBranch")
        set(value) {
        _builder.branch = value
      }
    /**
     * `string branch = 4;`
     */
    public fun clearBranch() {
      _builder.clearBranch()
    }

    /**
     * `string comment = 5;`
     */
    public var comment: kotlin.String
      @kotlin.jvm.JvmName("getComment")
        get() = _builder.comment
      @kotlin.jvm.JvmName("setComment")
        set(value) {
        _builder.comment = value
      }
    /**
     * `string comment = 5;`
     */
    public fun clearComment() {
      _builder.clearComment()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.FirmwareVersion.copy(block: `focstim_rpc`.FirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.FirmwareVersion =
  `focstim_rpc`.FirmwareVersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

