// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationDebugAS5311")
public inline fun notificationDebugAS5311(block: focstim_rpc.NotificationDebugAS5311Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugAS5311 =
  focstim_rpc.NotificationDebugAS5311Kt.Dsl._create(focstim_rpc.Notifications.NotificationDebugAS5311.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationDebugAS5311`
 */
public object NotificationDebugAS5311Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationDebugAS5311.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationDebugAS5311.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationDebugAS5311 = _builder.build()

    /**
     * `int32 raw = 1;`
     */
    public var raw: kotlin.Int
      @kotlin.jvm.JvmName("getRaw")
        get() = _builder.raw
      @kotlin.jvm.JvmName("setRaw")
        set(value) {
        _builder.raw = value
      }
    /**
     * `int32 raw = 1;`
     */
    public fun clearRaw() {
      _builder.clearRaw()
    }

    /**
     * `sint32 tracked = 2;`
     */
    public var tracked: kotlin.Int
      @kotlin.jvm.JvmName("getTracked")
        get() = _builder.tracked
      @kotlin.jvm.JvmName("setTracked")
        set(value) {
        _builder.tracked = value
      }
    /**
     * `sint32 tracked = 2;`
     */
    public fun clearTracked() {
      _builder.clearTracked()
    }

    /**
     * `int32 flags = 3;`
     */
    public var flags: kotlin.Int
      @kotlin.jvm.JvmName("getFlags")
        get() = _builder.flags
      @kotlin.jvm.JvmName("setFlags")
        set(value) {
        _builder.flags = value
      }
    /**
     * `int32 flags = 3;`
     */
    public fun clearFlags() {
      _builder.clearFlags()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationDebugAS5311.copy(block: `focstim_rpc`.NotificationDebugAS5311Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugAS5311 =
  `focstim_rpc`.NotificationDebugAS5311Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

