// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: focstim_rpc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotification")
public inline fun notification(block: focstim_rpc.NotificationKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Notification =
  focstim_rpc.NotificationKt.Dsl._create(focstim_rpc.FocstimRpc.Notification.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.Notification`
 */
public object NotificationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.FocstimRpc.Notification.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.FocstimRpc.Notification.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.FocstimRpc.Notification = _builder.build()

    /**
     * `.focstim_rpc.NotificationBoot notification_boot = 1;`
     */
    public var notificationBoot: focstim_rpc.Notifications.NotificationBoot
      @kotlin.jvm.JvmName("getNotificationBoot")
        get() = _builder.notificationBoot
      @kotlin.jvm.JvmName("setNotificationBoot")
        set(value) {
        _builder.notificationBoot = value
      }
    /**
     * `.focstim_rpc.NotificationBoot notification_boot = 1;`
     */
    public fun clearNotificationBoot() {
      _builder.clearNotificationBoot()
    }
    /**
     * `.focstim_rpc.NotificationBoot notification_boot = 1;`
     * @return Whether the notificationBoot field is set.
     */
    public fun hasNotificationBoot(): kotlin.Boolean {
      return _builder.hasNotificationBoot()
    }

    /**
     * `.focstim_rpc.NotificationDeviceVolume notification_device_volume = 2;`
     */
    public var notificationDeviceVolume: focstim_rpc.Notifications.NotificationDeviceVolume
      @kotlin.jvm.JvmName("getNotificationDeviceVolume")
        get() = _builder.notificationDeviceVolume
      @kotlin.jvm.JvmName("setNotificationDeviceVolume")
        set(value) {
        _builder.notificationDeviceVolume = value
      }
    /**
     * `.focstim_rpc.NotificationDeviceVolume notification_device_volume = 2;`
     */
    public fun clearNotificationDeviceVolume() {
      _builder.clearNotificationDeviceVolume()
    }
    /**
     * `.focstim_rpc.NotificationDeviceVolume notification_device_volume = 2;`
     * @return Whether the notificationDeviceVolume field is set.
     */
    public fun hasNotificationDeviceVolume(): kotlin.Boolean {
      return _builder.hasNotificationDeviceVolume()
    }

    /**
     * `.focstim_rpc.NotificationCurrents notification_currents = 3;`
     */
    public var notificationCurrents: focstim_rpc.Notifications.NotificationCurrents
      @kotlin.jvm.JvmName("getNotificationCurrents")
        get() = _builder.notificationCurrents
      @kotlin.jvm.JvmName("setNotificationCurrents")
        set(value) {
        _builder.notificationCurrents = value
      }
    /**
     * `.focstim_rpc.NotificationCurrents notification_currents = 3;`
     */
    public fun clearNotificationCurrents() {
      _builder.clearNotificationCurrents()
    }
    /**
     * `.focstim_rpc.NotificationCurrents notification_currents = 3;`
     * @return Whether the notificationCurrents field is set.
     */
    public fun hasNotificationCurrents(): kotlin.Boolean {
      return _builder.hasNotificationCurrents()
    }

    /**
     * `.focstim_rpc.NotificationOutputResistance notification_output_resistance = 4;`
     */
    public var notificationOutputResistance: focstim_rpc.Notifications.NotificationOutputResistance
      @kotlin.jvm.JvmName("getNotificationOutputResistance")
        get() = _builder.notificationOutputResistance
      @kotlin.jvm.JvmName("setNotificationOutputResistance")
        set(value) {
        _builder.notificationOutputResistance = value
      }
    /**
     * `.focstim_rpc.NotificationOutputResistance notification_output_resistance = 4;`
     */
    public fun clearNotificationOutputResistance() {
      _builder.clearNotificationOutputResistance()
    }
    /**
     * `.focstim_rpc.NotificationOutputResistance notification_output_resistance = 4;`
     * @return Whether the notificationOutputResistance field is set.
     */
    public fun hasNotificationOutputResistance(): kotlin.Boolean {
      return _builder.hasNotificationOutputResistance()
    }

    /**
     * `.focstim_rpc.NotificationSkinResistance notification_skin_resistance = 11;`
     */
    public var notificationSkinResistance: focstim_rpc.Notifications.NotificationSkinResistance
      @kotlin.jvm.JvmName("getNotificationSkinResistance")
        get() = _builder.notificationSkinResistance
      @kotlin.jvm.JvmName("setNotificationSkinResistance")
        set(value) {
        _builder.notificationSkinResistance = value
      }
    /**
     * `.focstim_rpc.NotificationSkinResistance notification_skin_resistance = 11;`
     */
    public fun clearNotificationSkinResistance() {
      _builder.clearNotificationSkinResistance()
    }
    /**
     * `.focstim_rpc.NotificationSkinResistance notification_skin_resistance = 11;`
     * @return Whether the notificationSkinResistance field is set.
     */
    public fun hasNotificationSkinResistance(): kotlin.Boolean {
      return _builder.hasNotificationSkinResistance()
    }

    /**
     * `.focstim_rpc.NotificationSystemStats notification_system_stats = 5;`
     */
    public var notificationSystemStats: focstim_rpc.Notifications.NotificationSystemStats
      @kotlin.jvm.JvmName("getNotificationSystemStats")
        get() = _builder.notificationSystemStats
      @kotlin.jvm.JvmName("setNotificationSystemStats")
        set(value) {
        _builder.notificationSystemStats = value
      }
    /**
     * `.focstim_rpc.NotificationSystemStats notification_system_stats = 5;`
     */
    public fun clearNotificationSystemStats() {
      _builder.clearNotificationSystemStats()
    }
    /**
     * `.focstim_rpc.NotificationSystemStats notification_system_stats = 5;`
     * @return Whether the notificationSystemStats field is set.
     */
    public fun hasNotificationSystemStats(): kotlin.Boolean {
      return _builder.hasNotificationSystemStats()
    }

    /**
     * `.focstim_rpc.NotificationSignalStats notification_signal_stats = 6;`
     */
    public var notificationSignalStats: focstim_rpc.Notifications.NotificationSignalStats
      @kotlin.jvm.JvmName("getNotificationSignalStats")
        get() = _builder.notificationSignalStats
      @kotlin.jvm.JvmName("setNotificationSignalStats")
        set(value) {
        _builder.notificationSignalStats = value
      }
    /**
     * `.focstim_rpc.NotificationSignalStats notification_signal_stats = 6;`
     */
    public fun clearNotificationSignalStats() {
      _builder.clearNotificationSignalStats()
    }
    /**
     * `.focstim_rpc.NotificationSignalStats notification_signal_stats = 6;`
     * @return Whether the notificationSignalStats field is set.
     */
    public fun hasNotificationSignalStats(): kotlin.Boolean {
      return _builder.hasNotificationSignalStats()
    }

    /**
     * `.focstim_rpc.NotificationBattery notification_battery = 7;`
     */
    public var notificationBattery: focstim_rpc.Notifications.NotificationBattery
      @kotlin.jvm.JvmName("getNotificationBattery")
        get() = _builder.notificationBattery
      @kotlin.jvm.JvmName("setNotificationBattery")
        set(value) {
        _builder.notificationBattery = value
      }
    /**
     * `.focstim_rpc.NotificationBattery notification_battery = 7;`
     */
    public fun clearNotificationBattery() {
      _builder.clearNotificationBattery()
    }
    /**
     * `.focstim_rpc.NotificationBattery notification_battery = 7;`
     * @return Whether the notificationBattery field is set.
     */
    public fun hasNotificationBattery(): kotlin.Boolean {
      return _builder.hasNotificationBattery()
    }

    /**
     * `.focstim_rpc.NotificationLSM6DSOX notification_lsm6dsox = 8;`
     */
    public var notificationLsm6Dsox: focstim_rpc.Notifications.NotificationLSM6DSOX
      @kotlin.jvm.JvmName("getNotificationLsm6Dsox")
        get() = _builder.notificationLsm6Dsox
      @kotlin.jvm.JvmName("setNotificationLsm6Dsox")
        set(value) {
        _builder.notificationLsm6Dsox = value
      }
    /**
     * `.focstim_rpc.NotificationLSM6DSOX notification_lsm6dsox = 8;`
     */
    public fun clearNotificationLsm6Dsox() {
      _builder.clearNotificationLsm6Dsox()
    }
    /**
     * `.focstim_rpc.NotificationLSM6DSOX notification_lsm6dsox = 8;`
     * @return Whether the notificationLsm6dsox field is set.
     */
    public fun hasNotificationLsm6Dsox(): kotlin.Boolean {
      return _builder.hasNotificationLsm6Dsox()
    }

    /**
     * `.focstim_rpc.NotificationPressure notification_pressure = 9;`
     */
    public var notificationPressure: focstim_rpc.Notifications.NotificationPressure
      @kotlin.jvm.JvmName("getNotificationPressure")
        get() = _builder.notificationPressure
      @kotlin.jvm.JvmName("setNotificationPressure")
        set(value) {
        _builder.notificationPressure = value
      }
    /**
     * `.focstim_rpc.NotificationPressure notification_pressure = 9;`
     */
    public fun clearNotificationPressure() {
      _builder.clearNotificationPressure()
    }
    /**
     * `.focstim_rpc.NotificationPressure notification_pressure = 9;`
     * @return Whether the notificationPressure field is set.
     */
    public fun hasNotificationPressure(): kotlin.Boolean {
      return _builder.hasNotificationPressure()
    }

    /**
     * `.focstim_rpc.NotificationButtonPress notification_button_press = 10;`
     */
    public var notificationButtonPress: focstim_rpc.Notifications.NotificationButtonPress
      @kotlin.jvm.JvmName("getNotificationButtonPress")
        get() = _builder.notificationButtonPress
      @kotlin.jvm.JvmName("setNotificationButtonPress")
        set(value) {
        _builder.notificationButtonPress = value
      }
    /**
     * `.focstim_rpc.NotificationButtonPress notification_button_press = 10;`
     */
    public fun clearNotificationButtonPress() {
      _builder.clearNotificationButtonPress()
    }
    /**
     * `.focstim_rpc.NotificationButtonPress notification_button_press = 10;`
     * @return Whether the notificationButtonPress field is set.
     */
    public fun hasNotificationButtonPress(): kotlin.Boolean {
      return _builder.hasNotificationButtonPress()
    }

    /**
     * `.focstim_rpc.NotificationDebugString notification_debug_string = 1000;`
     */
    public var notificationDebugString: focstim_rpc.Notifications.NotificationDebugString
      @kotlin.jvm.JvmName("getNotificationDebugString")
        get() = _builder.notificationDebugString
      @kotlin.jvm.JvmName("setNotificationDebugString")
        set(value) {
        _builder.notificationDebugString = value
      }
    /**
     * `.focstim_rpc.NotificationDebugString notification_debug_string = 1000;`
     */
    public fun clearNotificationDebugString() {
      _builder.clearNotificationDebugString()
    }
    /**
     * `.focstim_rpc.NotificationDebugString notification_debug_string = 1000;`
     * @return Whether the notificationDebugString field is set.
     */
    public fun hasNotificationDebugString(): kotlin.Boolean {
      return _builder.hasNotificationDebugString()
    }

    /**
     * `.focstim_rpc.NotificationDebugAS5311 notification_debug_as5311 = 1001;`
     */
    public var notificationDebugAs5311: focstim_rpc.Notifications.NotificationDebugAS5311
      @kotlin.jvm.JvmName("getNotificationDebugAs5311")
        get() = _builder.notificationDebugAs5311
      @kotlin.jvm.JvmName("setNotificationDebugAs5311")
        set(value) {
        _builder.notificationDebugAs5311 = value
      }
    /**
     * `.focstim_rpc.NotificationDebugAS5311 notification_debug_as5311 = 1001;`
     */
    public fun clearNotificationDebugAs5311() {
      _builder.clearNotificationDebugAs5311()
    }
    /**
     * `.focstim_rpc.NotificationDebugAS5311 notification_debug_as5311 = 1001;`
     * @return Whether the notificationDebugAs5311 field is set.
     */
    public fun hasNotificationDebugAs5311(): kotlin.Boolean {
      return _builder.hasNotificationDebugAs5311()
    }

    /**
     * `.focstim_rpc.NotificationDebugEdging notification_debug_edging = 1002;`
     */
    public var notificationDebugEdging: focstim_rpc.Notifications.NotificationDebugEdging
      @kotlin.jvm.JvmName("getNotificationDebugEdging")
        get() = _builder.notificationDebugEdging
      @kotlin.jvm.JvmName("setNotificationDebugEdging")
        set(value) {
        _builder.notificationDebugEdging = value
      }
    /**
     * `.focstim_rpc.NotificationDebugEdging notification_debug_edging = 1002;`
     */
    public fun clearNotificationDebugEdging() {
      _builder.clearNotificationDebugEdging()
    }
    /**
     * `.focstim_rpc.NotificationDebugEdging notification_debug_edging = 1002;`
     * @return Whether the notificationDebugEdging field is set.
     */
    public fun hasNotificationDebugEdging(): kotlin.Boolean {
      return _builder.hasNotificationDebugEdging()
    }

    /**
     * `.focstim_rpc.NotificationDebugTeleplot notification_debug_teleplot = 1003;`
     */
    public var notificationDebugTeleplot: focstim_rpc.Notifications.NotificationDebugTeleplot
      @kotlin.jvm.JvmName("getNotificationDebugTeleplot")
        get() = _builder.notificationDebugTeleplot
      @kotlin.jvm.JvmName("setNotificationDebugTeleplot")
        set(value) {
        _builder.notificationDebugTeleplot = value
      }
    /**
     * `.focstim_rpc.NotificationDebugTeleplot notification_debug_teleplot = 1003;`
     */
    public fun clearNotificationDebugTeleplot() {
      _builder.clearNotificationDebugTeleplot()
    }
    /**
     * `.focstim_rpc.NotificationDebugTeleplot notification_debug_teleplot = 1003;`
     * @return Whether the notificationDebugTeleplot field is set.
     */
    public fun hasNotificationDebugTeleplot(): kotlin.Boolean {
      return _builder.hasNotificationDebugTeleplot()
    }

    /**
     * `uint64 timestamp = 999;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `uint64 timestamp = 999;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    public val notificationCase: focstim_rpc.FocstimRpc.Notification.NotificationCase
    @kotlin.jvm.JvmName("getNotificationCase")
      get() = _builder.getNotificationCase()

    public fun clearNotification() {
      _builder.clearNotification()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.FocstimRpc.Notification.copy(block: `focstim_rpc`.NotificationKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Notification =
  `focstim_rpc`.NotificationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationBootOrNull: focstim_rpc.Notifications.NotificationBoot?
  get() = if (hasNotificationBoot()) getNotificationBoot() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationDeviceVolumeOrNull: focstim_rpc.Notifications.NotificationDeviceVolume?
  get() = if (hasNotificationDeviceVolume()) getNotificationDeviceVolume() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationCurrentsOrNull: focstim_rpc.Notifications.NotificationCurrents?
  get() = if (hasNotificationCurrents()) getNotificationCurrents() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationOutputResistanceOrNull: focstim_rpc.Notifications.NotificationOutputResistance?
  get() = if (hasNotificationOutputResistance()) getNotificationOutputResistance() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationSkinResistanceOrNull: focstim_rpc.Notifications.NotificationSkinResistance?
  get() = if (hasNotificationSkinResistance()) getNotificationSkinResistance() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationSystemStatsOrNull: focstim_rpc.Notifications.NotificationSystemStats?
  get() = if (hasNotificationSystemStats()) getNotificationSystemStats() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationSignalStatsOrNull: focstim_rpc.Notifications.NotificationSignalStats?
  get() = if (hasNotificationSignalStats()) getNotificationSignalStats() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationBatteryOrNull: focstim_rpc.Notifications.NotificationBattery?
  get() = if (hasNotificationBattery()) getNotificationBattery() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationLsm6DsoxOrNull: focstim_rpc.Notifications.NotificationLSM6DSOX?
  get() = if (hasNotificationLsm6Dsox()) getNotificationLsm6Dsox() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationPressureOrNull: focstim_rpc.Notifications.NotificationPressure?
  get() = if (hasNotificationPressure()) getNotificationPressure() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationButtonPressOrNull: focstim_rpc.Notifications.NotificationButtonPress?
  get() = if (hasNotificationButtonPress()) getNotificationButtonPress() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationDebugStringOrNull: focstim_rpc.Notifications.NotificationDebugString?
  get() = if (hasNotificationDebugString()) getNotificationDebugString() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationDebugAs5311OrNull: focstim_rpc.Notifications.NotificationDebugAS5311?
  get() = if (hasNotificationDebugAs5311()) getNotificationDebugAs5311() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationDebugEdgingOrNull: focstim_rpc.Notifications.NotificationDebugEdging?
  get() = if (hasNotificationDebugEdging()) getNotificationDebugEdging() else null

public val focstim_rpc.FocstimRpc.NotificationOrBuilder.notificationDebugTeleplotOrNull: focstim_rpc.Notifications.NotificationDebugTeleplot?
  get() = if (hasNotificationDebugTeleplot()) getNotificationDebugTeleplot() else null

