// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationDebugString")
public inline fun notificationDebugString(block: focstim_rpc.NotificationDebugStringKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugString =
  focstim_rpc.NotificationDebugStringKt.Dsl._create(focstim_rpc.Notifications.NotificationDebugString.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationDebugString`
 */
public object NotificationDebugStringKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationDebugString.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationDebugString.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationDebugString = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationDebugString.copy(block: `focstim_rpc`.NotificationDebugStringKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugString =
  `focstim_rpc`.NotificationDebugStringKt.Dsl._create(this.toBuilder()).apply { block() }._build()

