// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationPressure")
public inline fun notificationPressure(block: focstim_rpc.NotificationPressureKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationPressure =
  focstim_rpc.NotificationPressureKt.Dsl._create(focstim_rpc.Notifications.NotificationPressure.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationPressure`
 */
public object NotificationPressureKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationPressure.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationPressure.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationPressure = _builder.build()

    /**
     * ```
     * Pascal
     * ```
     *
     * `float pressure = 1;`
     */
    public var pressure: kotlin.Float
      @kotlin.jvm.JvmName("getPressure")
        get() = _builder.pressure
      @kotlin.jvm.JvmName("setPressure")
        set(value) {
        _builder.pressure = value
      }
    /**
     * ```
     * Pascal
     * ```
     *
     * `float pressure = 1;`
     */
    public fun clearPressure() {
      _builder.clearPressure()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationPressure.copy(block: `focstim_rpc`.NotificationPressureKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationPressure =
  `focstim_rpc`.NotificationPressureKt.Dsl._create(this.toBuilder()).apply { block() }._build()

