// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationSystemStats")
public inline fun notificationSystemStats(block: focstim_rpc.NotificationSystemStatsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSystemStats =
  focstim_rpc.NotificationSystemStatsKt.Dsl._create(focstim_rpc.Notifications.NotificationSystemStats.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationSystemStats`
 */
public object NotificationSystemStatsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationSystemStats.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationSystemStats.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationSystemStats = _builder.build()

    /**
     * `.focstim_rpc.SystemStatsESC1 esc1 = 1;`
     */
    public var esc1: focstim_rpc.Notifications.SystemStatsESC1
      @kotlin.jvm.JvmName("getEsc1")
        get() = _builder.esc1
      @kotlin.jvm.JvmName("setEsc1")
        set(value) {
        _builder.esc1 = value
      }
    /**
     * `.focstim_rpc.SystemStatsESC1 esc1 = 1;`
     */
    public fun clearEsc1() {
      _builder.clearEsc1()
    }
    /**
     * `.focstim_rpc.SystemStatsESC1 esc1 = 1;`
     * @return Whether the esc1 field is set.
     */
    public fun hasEsc1(): kotlin.Boolean {
      return _builder.hasEsc1()
    }

    /**
     * `.focstim_rpc.SystemStatsFocstimV3 focstimv3 = 2;`
     */
    public var focstimv3: focstim_rpc.Notifications.SystemStatsFocstimV3
      @kotlin.jvm.JvmName("getFocstimv3")
        get() = _builder.focstimv3
      @kotlin.jvm.JvmName("setFocstimv3")
        set(value) {
        _builder.focstimv3 = value
      }
    /**
     * `.focstim_rpc.SystemStatsFocstimV3 focstimv3 = 2;`
     */
    public fun clearFocstimv3() {
      _builder.clearFocstimv3()
    }
    /**
     * `.focstim_rpc.SystemStatsFocstimV3 focstimv3 = 2;`
     * @return Whether the focstimv3 field is set.
     */
    public fun hasFocstimv3(): kotlin.Boolean {
      return _builder.hasFocstimv3()
    }
    public val systemCase: focstim_rpc.Notifications.NotificationSystemStats.SystemCase
    @kotlin.jvm.JvmName("getSystemCase")
      get() = _builder.getSystemCase()

    public fun clearSystem() {
      _builder.clearSystem()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationSystemStats.copy(block: `focstim_rpc`.NotificationSystemStatsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSystemStats =
  `focstim_rpc`.NotificationSystemStatsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.Notifications.NotificationSystemStatsOrBuilder.esc1OrNull: focstim_rpc.Notifications.SystemStatsESC1?
  get() = if (hasEsc1()) getEsc1() else null

public val focstim_rpc.Notifications.NotificationSystemStatsOrBuilder.focstimv3OrNull: focstim_rpc.Notifications.SystemStatsFocstimV3?
  get() = if (hasFocstimv3()) getFocstimv3() else null

