// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationSkinResistance")
public inline fun notificationSkinResistance(block: focstim_rpc.NotificationSkinResistanceKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSkinResistance =
  focstim_rpc.NotificationSkinResistanceKt.Dsl._create(focstim_rpc.Notifications.NotificationSkinResistance.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationSkinResistance`
 */
public object NotificationSkinResistanceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationSkinResistance.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationSkinResistance.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationSkinResistance = _builder.build()

    /**
     * ```
     * best-guess estimate of the skin resistance for display to user.
     * At the current carrier frequency.
     * Quite inaccurate on V1 due to nonstandard components.
     * ```
     *
     * `float resistance_a = 1;`
     */
    public var resistanceA: kotlin.Float
      @kotlin.jvm.JvmName("getResistanceA")
        get() = _builder.resistanceA
      @kotlin.jvm.JvmName("setResistanceA")
        set(value) {
        _builder.resistanceA = value
      }
    /**
     * ```
     * best-guess estimate of the skin resistance for display to user.
     * At the current carrier frequency.
     * Quite inaccurate on V1 due to nonstandard components.
     * ```
     *
     * `float resistance_a = 1;`
     */
    public fun clearResistanceA() {
      _builder.clearResistanceA()
    }

    /**
     * `float reluctance_a = 2;`
     */
    public var reluctanceA: kotlin.Float
      @kotlin.jvm.JvmName("getReluctanceA")
        get() = _builder.reluctanceA
      @kotlin.jvm.JvmName("setReluctanceA")
        set(value) {
        _builder.reluctanceA = value
      }
    /**
     * `float reluctance_a = 2;`
     */
    public fun clearReluctanceA() {
      _builder.clearReluctanceA()
    }

    /**
     * `float resistance_b = 3;`
     */
    public var resistanceB: kotlin.Float
      @kotlin.jvm.JvmName("getResistanceB")
        get() = _builder.resistanceB
      @kotlin.jvm.JvmName("setResistanceB")
        set(value) {
        _builder.resistanceB = value
      }
    /**
     * `float resistance_b = 3;`
     */
    public fun clearResistanceB() {
      _builder.clearResistanceB()
    }

    /**
     * `float reluctance_b = 4;`
     */
    public var reluctanceB: kotlin.Float
      @kotlin.jvm.JvmName("getReluctanceB")
        get() = _builder.reluctanceB
      @kotlin.jvm.JvmName("setReluctanceB")
        set(value) {
        _builder.reluctanceB = value
      }
    /**
     * `float reluctance_b = 4;`
     */
    public fun clearReluctanceB() {
      _builder.clearReluctanceB()
    }

    /**
     * `float resistance_c = 5;`
     */
    public var resistanceC: kotlin.Float
      @kotlin.jvm.JvmName("getResistanceC")
        get() = _builder.resistanceC
      @kotlin.jvm.JvmName("setResistanceC")
        set(value) {
        _builder.resistanceC = value
      }
    /**
     * `float resistance_c = 5;`
     */
    public fun clearResistanceC() {
      _builder.clearResistanceC()
    }

    /**
     * `float reluctance_c = 6;`
     */
    public var reluctanceC: kotlin.Float
      @kotlin.jvm.JvmName("getReluctanceC")
        get() = _builder.reluctanceC
      @kotlin.jvm.JvmName("setReluctanceC")
        set(value) {
        _builder.reluctanceC = value
      }
    /**
     * `float reluctance_c = 6;`
     */
    public fun clearReluctanceC() {
      _builder.clearReluctanceC()
    }

    /**
     * `float resistance_d = 7;`
     */
    public var resistanceD: kotlin.Float
      @kotlin.jvm.JvmName("getResistanceD")
        get() = _builder.resistanceD
      @kotlin.jvm.JvmName("setResistanceD")
        set(value) {
        _builder.resistanceD = value
      }
    /**
     * `float resistance_d = 7;`
     */
    public fun clearResistanceD() {
      _builder.clearResistanceD()
    }

    /**
     * `float reluctance_d = 8;`
     */
    public var reluctanceD: kotlin.Float
      @kotlin.jvm.JvmName("getReluctanceD")
        get() = _builder.reluctanceD
      @kotlin.jvm.JvmName("setReluctanceD")
        set(value) {
        _builder.reluctanceD = value
      }
    /**
     * `float reluctance_d = 8;`
     */
    public fun clearReluctanceD() {
      _builder.clearReluctanceD()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationSkinResistance.copy(block: `focstim_rpc`.NotificationSkinResistanceKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSkinResistance =
  `focstim_rpc`.NotificationSkinResistanceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

