// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationDebugEdging")
public inline fun notificationDebugEdging(block: focstim_rpc.NotificationDebugEdgingKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugEdging =
  focstim_rpc.NotificationDebugEdgingKt.Dsl._create(focstim_rpc.Notifications.NotificationDebugEdging.newBuilder()).apply { block() }._build()
/**
 * ```
 * only used for debug logging in restim
 * ```
 *
 * Protobuf type `focstim_rpc.NotificationDebugEdging`
 */
public object NotificationDebugEdgingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationDebugEdging.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationDebugEdging.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationDebugEdging = _builder.build()

    /**
     * `float full_power_threshold = 1;`
     */
    public var fullPowerThreshold: kotlin.Float
      @kotlin.jvm.JvmName("getFullPowerThreshold")
        get() = _builder.fullPowerThreshold
      @kotlin.jvm.JvmName("setFullPowerThreshold")
        set(value) {
        _builder.fullPowerThreshold = value
      }
    /**
     * `float full_power_threshold = 1;`
     */
    public fun clearFullPowerThreshold() {
      _builder.clearFullPowerThreshold()
    }

    /**
     * `float reduced_power_threshold = 2;`
     */
    public var reducedPowerThreshold: kotlin.Float
      @kotlin.jvm.JvmName("getReducedPowerThreshold")
        get() = _builder.reducedPowerThreshold
      @kotlin.jvm.JvmName("setReducedPowerThreshold")
        set(value) {
        _builder.reducedPowerThreshold = value
      }
    /**
     * `float reduced_power_threshold = 2;`
     */
    public fun clearReducedPowerThreshold() {
      _builder.clearReducedPowerThreshold()
    }

    /**
     * `float reduction = 3;`
     */
    public var reduction: kotlin.Float
      @kotlin.jvm.JvmName("getReduction")
        get() = _builder.reduction
      @kotlin.jvm.JvmName("setReduction")
        set(value) {
        _builder.reduction = value
      }
    /**
     * `float reduction = 3;`
     */
    public fun clearReduction() {
      _builder.clearReduction()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationDebugEdging.copy(block: `focstim_rpc`.NotificationDebugEdgingKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugEdging =
  `focstim_rpc`.NotificationDebugEdgingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

