// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationSignalStats")
public inline fun notificationSignalStats(block: focstim_rpc.NotificationSignalStatsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSignalStats =
  focstim_rpc.NotificationSignalStatsKt.Dsl._create(focstim_rpc.Notifications.NotificationSignalStats.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationSignalStats`
 */
public object NotificationSignalStatsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationSignalStats.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationSignalStats.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationSignalStats = _builder.build()

    /**
     * `float actual_pulse_frequency = 1;`
     */
    public var actualPulseFrequency: kotlin.Float
      @kotlin.jvm.JvmName("getActualPulseFrequency")
        get() = _builder.actualPulseFrequency
      @kotlin.jvm.JvmName("setActualPulseFrequency")
        set(value) {
        _builder.actualPulseFrequency = value
      }
    /**
     * `float actual_pulse_frequency = 1;`
     */
    public fun clearActualPulseFrequency() {
      _builder.clearActualPulseFrequency()
    }

    /**
     * ```
     * maximum peak-to-peak voltage (low side)
     * ```
     *
     * `float v_drive = 2;`
     */
    public var vDrive: kotlin.Float
      @kotlin.jvm.JvmName("getVDrive")
        get() = _builder.vDrive
      @kotlin.jvm.JvmName("setVDrive")
        set(value) {
        _builder.vDrive = value
      }
    /**
     * ```
     * maximum peak-to-peak voltage (low side)
     * ```
     *
     * `float v_drive = 2;`
     */
    public fun clearVDrive() {
      _builder.clearVDrive()
    }

    /**
     * ```
     * 0-1 precentage of transformer saturation
     * ```
     *
     * `float transformer_utilization = 3;`
     */
    public var transformerUtilization: kotlin.Float
      @kotlin.jvm.JvmName("getTransformerUtilization")
        get() = _builder.transformerUtilization
      @kotlin.jvm.JvmName("setTransformerUtilization")
        set(value) {
        _builder.transformerUtilization = value
      }
    /**
     * ```
     * 0-1 precentage of transformer saturation
     * ```
     *
     * `float transformer_utilization = 3;`
     */
    public fun clearTransformerUtilization() {
      _builder.clearTransformerUtilization()
    }

    /**
     * ```
     * 0-1 percentage of maximum usable voltage
     * ```
     *
     * `float voltage_utilization = 4;`
     */
    public var voltageUtilization: kotlin.Float
      @kotlin.jvm.JvmName("getVoltageUtilization")
        get() = _builder.voltageUtilization
      @kotlin.jvm.JvmName("setVoltageUtilization")
        set(value) {
        _builder.voltageUtilization = value
      }
    /**
     * ```
     * 0-1 percentage of maximum usable voltage
     * ```
     *
     * `float voltage_utilization = 4;`
     */
    public fun clearVoltageUtilization() {
      _builder.clearVoltageUtilization()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationSignalStats.copy(block: `focstim_rpc`.NotificationSignalStatsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationSignalStats =
  `focstim_rpc`.NotificationSignalStatsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

