// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationCurrents")
public inline fun notificationCurrents(block: focstim_rpc.NotificationCurrentsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationCurrents =
  focstim_rpc.NotificationCurrentsKt.Dsl._create(focstim_rpc.Notifications.NotificationCurrents.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationCurrents`
 */
public object NotificationCurrentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationCurrents.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationCurrents.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationCurrents = _builder.build()

    /**
     * ```
     * body current in amps
     * ```
     *
     * `float rms_a = 1;`
     */
    public var rmsA: kotlin.Float
      @kotlin.jvm.JvmName("getRmsA")
        get() = _builder.rmsA
      @kotlin.jvm.JvmName("setRmsA")
        set(value) {
        _builder.rmsA = value
      }
    /**
     * ```
     * body current in amps
     * ```
     *
     * `float rms_a = 1;`
     */
    public fun clearRmsA() {
      _builder.clearRmsA()
    }

    /**
     * `float rms_b = 2;`
     */
    public var rmsB: kotlin.Float
      @kotlin.jvm.JvmName("getRmsB")
        get() = _builder.rmsB
      @kotlin.jvm.JvmName("setRmsB")
        set(value) {
        _builder.rmsB = value
      }
    /**
     * `float rms_b = 2;`
     */
    public fun clearRmsB() {
      _builder.clearRmsB()
    }

    /**
     * `float rms_c = 3;`
     */
    public var rmsC: kotlin.Float
      @kotlin.jvm.JvmName("getRmsC")
        get() = _builder.rmsC
      @kotlin.jvm.JvmName("setRmsC")
        set(value) {
        _builder.rmsC = value
      }
    /**
     * `float rms_c = 3;`
     */
    public fun clearRmsC() {
      _builder.clearRmsC()
    }

    /**
     * `float rms_d = 4;`
     */
    public var rmsD: kotlin.Float
      @kotlin.jvm.JvmName("getRmsD")
        get() = _builder.rmsD
      @kotlin.jvm.JvmName("setRmsD")
        set(value) {
        _builder.rmsD = value
      }
    /**
     * `float rms_d = 4;`
     */
    public fun clearRmsD() {
      _builder.clearRmsD()
    }

    /**
     * ```
     * peak body current in amps
     * ```
     *
     * `float peak_a = 5;`
     */
    public var peakA: kotlin.Float
      @kotlin.jvm.JvmName("getPeakA")
        get() = _builder.peakA
      @kotlin.jvm.JvmName("setPeakA")
        set(value) {
        _builder.peakA = value
      }
    /**
     * ```
     * peak body current in amps
     * ```
     *
     * `float peak_a = 5;`
     */
    public fun clearPeakA() {
      _builder.clearPeakA()
    }

    /**
     * `float peak_b = 6;`
     */
    public var peakB: kotlin.Float
      @kotlin.jvm.JvmName("getPeakB")
        get() = _builder.peakB
      @kotlin.jvm.JvmName("setPeakB")
        set(value) {
        _builder.peakB = value
      }
    /**
     * `float peak_b = 6;`
     */
    public fun clearPeakB() {
      _builder.clearPeakB()
    }

    /**
     * `float peak_c = 7;`
     */
    public var peakC: kotlin.Float
      @kotlin.jvm.JvmName("getPeakC")
        get() = _builder.peakC
      @kotlin.jvm.JvmName("setPeakC")
        set(value) {
        _builder.peakC = value
      }
    /**
     * `float peak_c = 7;`
     */
    public fun clearPeakC() {
      _builder.clearPeakC()
    }

    /**
     * `float peak_d = 8;`
     */
    public var peakD: kotlin.Float
      @kotlin.jvm.JvmName("getPeakD")
        get() = _builder.peakD
      @kotlin.jvm.JvmName("setPeakD")
        set(value) {
        _builder.peakD = value
      }
    /**
     * `float peak_d = 8;`
     */
    public fun clearPeakD() {
      _builder.clearPeakD()
    }

    /**
     * ```
     * output stage power in watts
     * ```
     *
     * `float output_power = 9;`
     */
    public var outputPower: kotlin.Float
      @kotlin.jvm.JvmName("getOutputPower")
        get() = _builder.outputPower
      @kotlin.jvm.JvmName("setOutputPower")
        set(value) {
        _builder.outputPower = value
      }
    /**
     * ```
     * output stage power in watts
     * ```
     *
     * `float output_power = 9;`
     */
    public fun clearOutputPower() {
      _builder.clearOutputPower()
    }

    /**
     * ```
     * output stage power in watts, only the component delivered to skin
     * ```
     *
     * `float output_power_skin = 10;`
     */
    public var outputPowerSkin: kotlin.Float
      @kotlin.jvm.JvmName("getOutputPowerSkin")
        get() = _builder.outputPowerSkin
      @kotlin.jvm.JvmName("setOutputPowerSkin")
        set(value) {
        _builder.outputPowerSkin = value
      }
    /**
     * ```
     * output stage power in watts, only the component delivered to skin
     * ```
     *
     * `float output_power_skin = 10;`
     */
    public fun clearOutputPowerSkin() {
      _builder.clearOutputPowerSkin()
    }

    /**
     * `float peak_cmd = 11;`
     */
    public var peakCmd: kotlin.Float
      @kotlin.jvm.JvmName("getPeakCmd")
        get() = _builder.peakCmd
      @kotlin.jvm.JvmName("setPeakCmd")
        set(value) {
        _builder.peakCmd = value
      }
    /**
     * `float peak_cmd = 11;`
     */
    public fun clearPeakCmd() {
      _builder.clearPeakCmd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationCurrents.copy(block: `focstim_rpc`.NotificationCurrentsKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationCurrents =
  `focstim_rpc`.NotificationCurrentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

