// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationBattery")
public inline fun notificationBattery(block: focstim_rpc.NotificationBatteryKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationBattery =
  focstim_rpc.NotificationBatteryKt.Dsl._create(focstim_rpc.Notifications.NotificationBattery.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationBattery`
 */
public object NotificationBatteryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationBattery.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationBattery.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationBattery = _builder.build()

    /**
     * `float battery_voltage = 1;`
     */
    public var batteryVoltage: kotlin.Float
      @kotlin.jvm.JvmName("getBatteryVoltage")
        get() = _builder.batteryVoltage
      @kotlin.jvm.JvmName("setBatteryVoltage")
        set(value) {
        _builder.batteryVoltage = value
      }
    /**
     * `float battery_voltage = 1;`
     */
    public fun clearBatteryVoltage() {
      _builder.clearBatteryVoltage()
    }

    /**
     * `float battery_charge_rate_watt = 2;`
     */
    public var batteryChargeRateWatt: kotlin.Float
      @kotlin.jvm.JvmName("getBatteryChargeRateWatt")
        get() = _builder.batteryChargeRateWatt
      @kotlin.jvm.JvmName("setBatteryChargeRateWatt")
        set(value) {
        _builder.batteryChargeRateWatt = value
      }
    /**
     * `float battery_charge_rate_watt = 2;`
     */
    public fun clearBatteryChargeRateWatt() {
      _builder.clearBatteryChargeRateWatt()
    }

    /**
     * ```
     * int?
     * ```
     *
     * `float battery_soc = 3;`
     */
    public var batterySoc: kotlin.Float
      @kotlin.jvm.JvmName("getBatterySoc")
        get() = _builder.batterySoc
      @kotlin.jvm.JvmName("setBatterySoc")
        set(value) {
        _builder.batterySoc = value
      }
    /**
     * ```
     * int?
     * ```
     *
     * `float battery_soc = 3;`
     */
    public fun clearBatterySoc() {
      _builder.clearBatterySoc()
    }

    /**
     * `bool wall_power_present = 4;`
     */
    public var wallPowerPresent: kotlin.Boolean
      @kotlin.jvm.JvmName("getWallPowerPresent")
        get() = _builder.wallPowerPresent
      @kotlin.jvm.JvmName("setWallPowerPresent")
        set(value) {
        _builder.wallPowerPresent = value
      }
    /**
     * `bool wall_power_present = 4;`
     */
    public fun clearWallPowerPresent() {
      _builder.clearWallPowerPresent()
    }

    /**
     * `float chip_temperature = 5;`
     */
    public var chipTemperature: kotlin.Float
      @kotlin.jvm.JvmName("getChipTemperature")
        get() = _builder.chipTemperature
      @kotlin.jvm.JvmName("setChipTemperature")
        set(value) {
        _builder.chipTemperature = value
      }
    /**
     * `float chip_temperature = 5;`
     */
    public fun clearChipTemperature() {
      _builder.clearChipTemperature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationBattery.copy(block: `focstim_rpc`.NotificationBatteryKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationBattery =
  `focstim_rpc`.NotificationBatteryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

