// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationDeviceVolume")
public inline fun notificationDeviceVolume(block: focstim_rpc.NotificationDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDeviceVolume =
  focstim_rpc.NotificationDeviceVolumeKt.Dsl._create(focstim_rpc.Notifications.NotificationDeviceVolume.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationDeviceVolume`
 */
public object NotificationDeviceVolumeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationDeviceVolume.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationDeviceVolume.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationDeviceVolume = _builder.build()

    /**
     * ```
     * (0, 1)
     * ```
     *
     * `float volume = 1;`
     */
    public var volume: kotlin.Float
      @kotlin.jvm.JvmName("getVolume")
        get() = _builder.volume
      @kotlin.jvm.JvmName("setVolume")
        set(value) {
        _builder.volume = value
      }
    /**
     * ```
     * (0, 1)
     * ```
     *
     * `float volume = 1;`
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * `bool locked = 2;`
     */
    public var locked: kotlin.Boolean
      @kotlin.jvm.JvmName("getLocked")
        get() = _builder.locked
      @kotlin.jvm.JvmName("setLocked")
        set(value) {
        _builder.locked = value
      }
    /**
     * `bool locked = 2;`
     */
    public fun clearLocked() {
      _builder.clearLocked()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationDeviceVolume.copy(block: `focstim_rpc`.NotificationDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDeviceVolume =
  `focstim_rpc`.NotificationDeviceVolumeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

