// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationBoot")
public inline fun notificationBoot(block: focstim_rpc.NotificationBootKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationBoot =
  focstim_rpc.NotificationBootKt.Dsl._create(focstim_rpc.Notifications.NotificationBoot.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationBoot`
 */
public object NotificationBootKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationBoot.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationBoot.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationBoot = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationBoot.copy(block: `focstim_rpc`.NotificationBootKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationBoot =
  `focstim_rpc`.NotificationBootKt.Dsl._create(this.toBuilder()).apply { block() }._build()

