// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationLSM6DSOX")
public inline fun notificationLSM6DSOX(block: focstim_rpc.NotificationLSM6DSOXKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationLSM6DSOX =
  focstim_rpc.NotificationLSM6DSOXKt.Dsl._create(focstim_rpc.Notifications.NotificationLSM6DSOX.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationLSM6DSOX`
 */
public object NotificationLSM6DSOXKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationLSM6DSOX.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationLSM6DSOX.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationLSM6DSOX = _builder.build()

    /**
     * ```
     * acceleration, conversion factor depends on full scale selection
     * ```
     *
     * `sint32 acc_x = 1;`
     */
    public var accX: kotlin.Int
      @kotlin.jvm.JvmName("getAccX")
        get() = _builder.accX
      @kotlin.jvm.JvmName("setAccX")
        set(value) {
        _builder.accX = value
      }
    /**
     * ```
     * acceleration, conversion factor depends on full scale selection
     * ```
     *
     * `sint32 acc_x = 1;`
     */
    public fun clearAccX() {
      _builder.clearAccX()
    }

    /**
     * `sint32 acc_y = 2;`
     */
    public var accY: kotlin.Int
      @kotlin.jvm.JvmName("getAccY")
        get() = _builder.accY
      @kotlin.jvm.JvmName("setAccY")
        set(value) {
        _builder.accY = value
      }
    /**
     * `sint32 acc_y = 2;`
     */
    public fun clearAccY() {
      _builder.clearAccY()
    }

    /**
     * `sint32 acc_z = 3;`
     */
    public var accZ: kotlin.Int
      @kotlin.jvm.JvmName("getAccZ")
        get() = _builder.accZ
      @kotlin.jvm.JvmName("setAccZ")
        set(value) {
        _builder.accZ = value
      }
    /**
     * `sint32 acc_z = 3;`
     */
    public fun clearAccZ() {
      _builder.clearAccZ()
    }

    /**
     * ```
     * angular velocity, conversion factor depends on full scale selection
     * ```
     *
     * `sint32 gyr_x = 4;`
     */
    public var gyrX: kotlin.Int
      @kotlin.jvm.JvmName("getGyrX")
        get() = _builder.gyrX
      @kotlin.jvm.JvmName("setGyrX")
        set(value) {
        _builder.gyrX = value
      }
    /**
     * ```
     * angular velocity, conversion factor depends on full scale selection
     * ```
     *
     * `sint32 gyr_x = 4;`
     */
    public fun clearGyrX() {
      _builder.clearGyrX()
    }

    /**
     * `sint32 gyr_y = 5;`
     */
    public var gyrY: kotlin.Int
      @kotlin.jvm.JvmName("getGyrY")
        get() = _builder.gyrY
      @kotlin.jvm.JvmName("setGyrY")
        set(value) {
        _builder.gyrY = value
      }
    /**
     * `sint32 gyr_y = 5;`
     */
    public fun clearGyrY() {
      _builder.clearGyrY()
    }

    /**
     * `sint32 gyr_z = 6;`
     */
    public var gyrZ: kotlin.Int
      @kotlin.jvm.JvmName("getGyrZ")
        get() = _builder.gyrZ
      @kotlin.jvm.JvmName("setGyrZ")
        set(value) {
        _builder.gyrZ = value
      }
    /**
     * `sint32 gyr_z = 6;`
     */
    public fun clearGyrZ() {
      _builder.clearGyrZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationLSM6DSOX.copy(block: `focstim_rpc`.NotificationLSM6DSOXKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationLSM6DSOX =
  `focstim_rpc`.NotificationLSM6DSOXKt.Dsl._create(this.toBuilder()).apply { block() }._build()

