// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationDebugTeleplot")
public inline fun notificationDebugTeleplot(block: focstim_rpc.NotificationDebugTeleplotKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugTeleplot =
  focstim_rpc.NotificationDebugTeleplotKt.Dsl._create(focstim_rpc.Notifications.NotificationDebugTeleplot.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationDebugTeleplot`
 */
public object NotificationDebugTeleplotKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationDebugTeleplot.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationDebugTeleplot.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationDebugTeleplot = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `float value = 2;`
     */
    public var value: kotlin.Float
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `float value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationDebugTeleplot.copy(block: `focstim_rpc`.NotificationDebugTeleplotKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationDebugTeleplot =
  `focstim_rpc`.NotificationDebugTeleplotKt.Dsl._create(this.toBuilder()).apply { block() }._build()

