// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializenotificationButtonPress")
public inline fun notificationButtonPress(block: focstim_rpc.NotificationButtonPressKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationButtonPress =
  focstim_rpc.NotificationButtonPressKt.Dsl._create(focstim_rpc.Notifications.NotificationButtonPress.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.NotificationButtonPress`
 */
public object NotificationButtonPressKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.NotificationButtonPress.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.NotificationButtonPress.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.NotificationButtonPress = _builder.build()

    /**
     * `.focstim_rpc.ButtonState state = 1;`
     */
    public var state: focstim_rpc.Constants.ButtonState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    public var stateValue: kotlin.Int
      @kotlin.jvm.JvmName("getStateValue")
        get() = _builder.stateValue
      @kotlin.jvm.JvmName("setStateValue")
        set(value) {
        _builder.stateValue = value
      }
    /**
     * `.focstim_rpc.ButtonState state = 1;`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * ```
     * millis() on STM32 (uint32_t, wraps ~49.7 days)
     * ```
     *
     * `uint32 timestamp_ms = 2;`
     */
    public var timestampMs: kotlin.Int
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * ```
     * millis() on STM32 (uint32_t, wraps ~49.7 days)
     * ```
     *
     * `uint32 timestamp_ms = 2;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.NotificationButtonPress.copy(block: `focstim_rpc`.NotificationButtonPressKt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.NotificationButtonPress =
  `focstim_rpc`.NotificationButtonPressKt.Dsl._create(this.toBuilder()).apply { block() }._build()

