// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestSignalStart")
public inline fun requestSignalStart(block: focstim_rpc.RequestSignalStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestSignalStart =
  focstim_rpc.RequestSignalStartKt.Dsl._create(focstim_rpc.Messages.RequestSignalStart.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestSignalStart`
 */
public object RequestSignalStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestSignalStart.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestSignalStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestSignalStart = _builder.build()

    /**
     * ```
     * todo: max power?
     * ```
     *
     * `.focstim_rpc.OutputMode mode = 1;`
     */
    public var mode: focstim_rpc.Constants.OutputMode
      @kotlin.jvm.JvmName("getMode")
        get() = _builder.mode
      @kotlin.jvm.JvmName("setMode")
        set(value) {
        _builder.mode = value
      }
    public var modeValue: kotlin.Int
      @kotlin.jvm.JvmName("getModeValue")
        get() = _builder.modeValue
      @kotlin.jvm.JvmName("setModeValue")
        set(value) {
        _builder.modeValue = value
      }
    /**
     * ```
     * todo: max power?
     * ```
     *
     * `.focstim_rpc.OutputMode mode = 1;`
     */
    public fun clearMode() {
      _builder.clearMode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestSignalStart.copy(block: `focstim_rpc`.RequestSignalStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestSignalStart =
  `focstim_rpc`.RequestSignalStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

