// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestLockDeviceVolume")
public inline fun requestLockDeviceVolume(block: focstim_rpc.RequestLockDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLockDeviceVolume =
  focstim_rpc.RequestLockDeviceVolumeKt.Dsl._create(focstim_rpc.Messages.RequestLockDeviceVolume.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestLockDeviceVolume`
 */
public object RequestLockDeviceVolumeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestLockDeviceVolume.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestLockDeviceVolume.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestLockDeviceVolume = _builder.build()

    /**
     * `bool lock = 1;`
     */
    public var lock: kotlin.Boolean
      @kotlin.jvm.JvmName("getLock")
        get() = _builder.lock
      @kotlin.jvm.JvmName("setLock")
        set(value) {
        _builder.lock = value
      }
    /**
     * `bool lock = 1;`
     */
    public fun clearLock() {
      _builder.clearLock()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestLockDeviceVolume.copy(block: `focstim_rpc`.RequestLockDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLockDeviceVolume =
  `focstim_rpc`.RequestLockDeviceVolumeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

