// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestLSM6DSOXStop")
public inline fun requestLSM6DSOXStop(block: focstim_rpc.RequestLSM6DSOXStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLSM6DSOXStop =
  focstim_rpc.RequestLSM6DSOXStopKt.Dsl._create(focstim_rpc.Messages.RequestLSM6DSOXStop.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestLSM6DSOXStop`
 */
public object RequestLSM6DSOXStopKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestLSM6DSOXStop.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestLSM6DSOXStop.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestLSM6DSOXStop = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestLSM6DSOXStop.copy(block: `focstim_rpc`.RequestLSM6DSOXStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLSM6DSOXStop =
  `focstim_rpc`.RequestLSM6DSOXStopKt.Dsl._create(this.toBuilder()).apply { block() }._build()

