// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestFirmwareVersion")
public inline fun requestFirmwareVersion(block: focstim_rpc.RequestFirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestFirmwareVersion =
  focstim_rpc.RequestFirmwareVersionKt.Dsl._create(focstim_rpc.Messages.RequestFirmwareVersion.newBuilder()).apply { block() }._build()
/**
 * ```
 * general commands
 * ```
 *
 * Protobuf type `focstim_rpc.RequestFirmwareVersion`
 */
public object RequestFirmwareVersionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestFirmwareVersion.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestFirmwareVersion.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestFirmwareVersion = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestFirmwareVersion.copy(block: `focstim_rpc`.RequestFirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestFirmwareVersion =
  `focstim_rpc`.RequestFirmwareVersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

