// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestSignalStop")
public inline fun requestSignalStop(block: focstim_rpc.RequestSignalStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestSignalStop =
  focstim_rpc.RequestSignalStopKt.Dsl._create(focstim_rpc.Messages.RequestSignalStop.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestSignalStop`
 */
public object RequestSignalStopKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestSignalStop.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestSignalStop.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestSignalStop = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestSignalStop.copy(block: `focstim_rpc`.RequestSignalStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestSignalStop =
  `focstim_rpc`.RequestSignalStopKt.Dsl._create(this.toBuilder()).apply { block() }._build()

