// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestAxisMoveTo")
public inline fun requestAxisMoveTo(block: focstim_rpc.RequestAxisMoveToKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestAxisMoveTo =
  focstim_rpc.RequestAxisMoveToKt.Dsl._create(focstim_rpc.Messages.RequestAxisMoveTo.newBuilder()).apply { block() }._build()
/**
 * ```
 * MoveTo streaming API
 * ```
 *
 * Protobuf type `focstim_rpc.RequestAxisMoveTo`
 */
public object RequestAxisMoveToKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestAxisMoveTo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestAxisMoveTo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestAxisMoveTo = _builder.build()

    /**
     * `.focstim_rpc.AxisType axis = 1;`
     */
    public var axis: focstim_rpc.Constants.AxisType
      @kotlin.jvm.JvmName("getAxis")
        get() = _builder.axis
      @kotlin.jvm.JvmName("setAxis")
        set(value) {
        _builder.axis = value
      }
    public var axisValue: kotlin.Int
      @kotlin.jvm.JvmName("getAxisValue")
        get() = _builder.axisValue
      @kotlin.jvm.JvmName("setAxisValue")
        set(value) {
        _builder.axisValue = value
      }
    /**
     * `.focstim_rpc.AxisType axis = 1;`
     */
    public fun clearAxis() {
      _builder.clearAxis()
    }

    /**
     * `float value = 3;`
     */
    public var value: kotlin.Float
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `float value = 3;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * ```
     * in ms
     * ```
     *
     * `uint32 interval = 4;`
     */
    public var interval: kotlin.Int
      @kotlin.jvm.JvmName("getInterval")
        get() = _builder.interval
      @kotlin.jvm.JvmName("setInterval")
        set(value) {
        _builder.interval = value
      }
    /**
     * ```
     * in ms
     * ```
     *
     * `uint32 interval = 4;`
     */
    public fun clearInterval() {
      _builder.clearInterval()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestAxisMoveTo.copy(block: `focstim_rpc`.RequestAxisMoveToKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestAxisMoveTo =
  `focstim_rpc`.RequestAxisMoveToKt.Dsl._create(this.toBuilder()).apply { block() }._build()

