// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestLSM6DSOXStart")
public inline fun requestLSM6DSOXStart(block: focstim_rpc.RequestLSM6DSOXStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLSM6DSOXStart =
  focstim_rpc.RequestLSM6DSOXStartKt.Dsl._create(focstim_rpc.Messages.RequestLSM6DSOXStart.newBuilder()).apply { block() }._build()
/**
 * ```
 * sensors
 * ```
 *
 * Protobuf type `focstim_rpc.RequestLSM6DSOXStart`
 */
public object RequestLSM6DSOXStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestLSM6DSOXStart.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestLSM6DSOXStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestLSM6DSOXStart = _builder.build()

    /**
     * ```
     * Available values are 12.5, 26, 52, 104, 208, 417, 833, 1667, 3333, 6667 Hz
     * ```
     *
     * `float imu_samplerate = 1;`
     */
    public var imuSamplerate: kotlin.Float
      @kotlin.jvm.JvmName("getImuSamplerate")
        get() = _builder.imuSamplerate
      @kotlin.jvm.JvmName("setImuSamplerate")
        set(value) {
        _builder.imuSamplerate = value
      }
    /**
     * ```
     * Available values are 12.5, 26, 52, 104, 208, 417, 833, 1667, 3333, 6667 Hz
     * ```
     *
     * `float imu_samplerate = 1;`
     */
    public fun clearImuSamplerate() {
      _builder.clearImuSamplerate()
    }

    /**
     * ```
     * Available values are: 2, 4, 8, 16 G
     * ```
     *
     * `float acc_fullscale = 2;`
     */
    public var accFullscale: kotlin.Float
      @kotlin.jvm.JvmName("getAccFullscale")
        get() = _builder.accFullscale
      @kotlin.jvm.JvmName("setAccFullscale")
        set(value) {
        _builder.accFullscale = value
      }
    /**
     * ```
     * Available values are: 2, 4, 8, 16 G
     * ```
     *
     * `float acc_fullscale = 2;`
     */
    public fun clearAccFullscale() {
      _builder.clearAccFullscale()
    }

    /**
     * ```
     * Available values are: 125, 250, 500, 1000, 2000 dps
     * ```
     *
     * `float gyr_fullscale = 3;`
     */
    public var gyrFullscale: kotlin.Float
      @kotlin.jvm.JvmName("getGyrFullscale")
        get() = _builder.gyrFullscale
      @kotlin.jvm.JvmName("setGyrFullscale")
        set(value) {
        _builder.gyrFullscale = value
      }
    /**
     * ```
     * Available values are: 125, 250, 500, 1000, 2000 dps
     * ```
     *
     * `float gyr_fullscale = 3;`
     */
    public fun clearGyrFullscale() {
      _builder.clearGyrFullscale()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestLSM6DSOXStart.copy(block: `focstim_rpc`.RequestLSM6DSOXStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestLSM6DSOXStart =
  `focstim_rpc`.RequestLSM6DSOXStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

