// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestDebugEnterBootloader")
public inline fun requestDebugEnterBootloader(block: focstim_rpc.RequestDebugEnterBootloaderKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestDebugEnterBootloader =
  focstim_rpc.RequestDebugEnterBootloaderKt.Dsl._create(focstim_rpc.Messages.RequestDebugEnterBootloader.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestDebugEnterBootloader`
 */
public object RequestDebugEnterBootloaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestDebugEnterBootloader.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestDebugEnterBootloader.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestDebugEnterBootloader = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestDebugEnterBootloader.copy(block: `focstim_rpc`.RequestDebugEnterBootloaderKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestDebugEnterBootloader =
  `focstim_rpc`.RequestDebugEnterBootloaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

