// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestTimestampSet")
public inline fun requestTimestampSet(block: focstim_rpc.RequestTimestampSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestTimestampSet =
  focstim_rpc.RequestTimestampSetKt.Dsl._create(focstim_rpc.Messages.RequestTimestampSet.newBuilder()).apply { block() }._build()
/**
 * ```
 * Tell the system what unix timestamp is. Call regularly to avoid drift.
 * ```
 *
 * Protobuf type `focstim_rpc.RequestTimestampSet`
 */
public object RequestTimestampSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestTimestampSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestTimestampSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestTimestampSet = _builder.build()

    /**
     * ```
     * unix timestamp
     * ```
     *
     * `uint64 timestamp_ms = 1;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * ```
     * unix timestamp
     * ```
     *
     * `uint64 timestamp_ms = 1;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestTimestampSet.copy(block: `focstim_rpc`.RequestTimestampSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestTimestampSet =
  `focstim_rpc`.RequestTimestampSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

