// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestTimestampGet")
public inline fun requestTimestampGet(block: focstim_rpc.RequestTimestampGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestTimestampGet =
  focstim_rpc.RequestTimestampGetKt.Dsl._create(focstim_rpc.Messages.RequestTimestampGet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestTimestampGet`
 */
public object RequestTimestampGetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestTimestampGet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestTimestampGet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestTimestampGet = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestTimestampGet.copy(block: `focstim_rpc`.RequestTimestampGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestTimestampGet =
  `focstim_rpc`.RequestTimestampGetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

