// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestDebugStm32DeepSleep")
public inline fun requestDebugStm32DeepSleep(block: focstim_rpc.RequestDebugStm32DeepSleepKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestDebugStm32DeepSleep =
  focstim_rpc.RequestDebugStm32DeepSleepKt.Dsl._create(focstim_rpc.Messages.RequestDebugStm32DeepSleep.newBuilder()).apply { block() }._build()
/**
 * ```
 * debug commands
 * ```
 *
 * Protobuf type `focstim_rpc.RequestDebugStm32DeepSleep`
 */
public object RequestDebugStm32DeepSleepKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestDebugStm32DeepSleep.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestDebugStm32DeepSleep.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestDebugStm32DeepSleep = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestDebugStm32DeepSleep.copy(block: `focstim_rpc`.RequestDebugStm32DeepSleepKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestDebugStm32DeepSleep =
  `focstim_rpc`.RequestDebugStm32DeepSleepKt.Dsl._create(this.toBuilder()).apply { block() }._build()

