// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestModeSet")
public inline fun requestModeSet(block: focstim_rpc.RequestModeSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestModeSet =
  focstim_rpc.RequestModeSetKt.Dsl._create(focstim_rpc.Messages.RequestModeSet.newBuilder()).apply { block() }._build()
/**
 * ```
 * TODO: implement?
 * ```
 *
 * Protobuf type `focstim_rpc.RequestModeSet`
 */
public object RequestModeSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestModeSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestModeSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestModeSet = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestModeSet.copy(block: `focstim_rpc`.RequestModeSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestModeSet =
  `focstim_rpc`.RequestModeSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

