// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestWifiParametersSet")
public inline fun requestWifiParametersSet(block: focstim_rpc.RequestWifiParametersSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestWifiParametersSet =
  focstim_rpc.RequestWifiParametersSetKt.Dsl._create(focstim_rpc.Messages.RequestWifiParametersSet.newBuilder()).apply { block() }._build()
/**
 * ```
 * network
 * ```
 *
 * Protobuf type `focstim_rpc.RequestWifiParametersSet`
 */
public object RequestWifiParametersSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestWifiParametersSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestWifiParametersSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestWifiParametersSet = _builder.build()

    /**
     * `bytes ssid = 1;`
     */
    public var ssid: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSsid")
        get() = _builder.ssid
      @kotlin.jvm.JvmName("setSsid")
        set(value) {
        _builder.ssid = value
      }
    /**
     * `bytes ssid = 1;`
     */
    public fun clearSsid() {
      _builder.clearSsid()
    }

    /**
     * `bytes password = 2;`
     */
    public var password: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPassword")
        get() = _builder.password
      @kotlin.jvm.JvmName("setPassword")
        set(value) {
        _builder.password = value
      }
    /**
     * `bytes password = 2;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestWifiParametersSet.copy(block: `focstim_rpc`.RequestWifiParametersSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestWifiParametersSet =
  `focstim_rpc`.RequestWifiParametersSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

