// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestAxisSet")
public inline fun requestAxisSet(block: focstim_rpc.RequestAxisSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestAxisSet =
  focstim_rpc.RequestAxisSetKt.Dsl._create(focstim_rpc.Messages.RequestAxisSet.newBuilder()).apply { block() }._build()
/**
 * ```
 * Buffered streaming API
 * ```
 *
 * Protobuf type `focstim_rpc.RequestAxisSet`
 */
public object RequestAxisSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestAxisSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestAxisSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestAxisSet = _builder.build()

    /**
     * `.focstim_rpc.AxisType axis = 1;`
     */
    public var axis: focstim_rpc.Constants.AxisType
      @kotlin.jvm.JvmName("getAxis")
        get() = _builder.axis
      @kotlin.jvm.JvmName("setAxis")
        set(value) {
        _builder.axis = value
      }
    public var axisValue: kotlin.Int
      @kotlin.jvm.JvmName("getAxisValue")
        get() = _builder.axisValue
      @kotlin.jvm.JvmName("setAxisValue")
        set(value) {
        _builder.axisValue = value
      }
    /**
     * `.focstim_rpc.AxisType axis = 1;`
     */
    public fun clearAxis() {
      _builder.clearAxis()
    }

    /**
     * ```
     * unix timestamp, in ms, modulo 2^32
     * ```
     *
     * `fixed32 timestamp_ms = 2;`
     */
    public var timestampMs: kotlin.Int
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * ```
     * unix timestamp, in ms, modulo 2^32
     * ```
     *
     * `fixed32 timestamp_ms = 2;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }

    /**
     * ```
     * ```
     *
     * `float value = 3;`
     */
    public var value: kotlin.Float
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * ```
     *
     * `float value = 3;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * `bool clear = 4;`
     */
    public var clear: kotlin.Boolean
      @kotlin.jvm.JvmName("getClear")
        get() = _builder.clear
      @kotlin.jvm.JvmName("setClear")
        set(value) {
        _builder.clear = value
      }
    /**
     * `bool clear = 4;`
     */
    public fun clearClear() {
      _builder.clearClear()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestAxisSet.copy(block: `focstim_rpc`.RequestAxisSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestAxisSet =
  `focstim_rpc`.RequestAxisSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

