// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequestCapabilitiesGet")
public inline fun requestCapabilitiesGet(block: focstim_rpc.RequestCapabilitiesGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestCapabilitiesGet =
  focstim_rpc.RequestCapabilitiesGetKt.Dsl._create(focstim_rpc.Messages.RequestCapabilitiesGet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RequestCapabilitiesGet`
 */
public object RequestCapabilitiesGetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.RequestCapabilitiesGet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.RequestCapabilitiesGet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.RequestCapabilitiesGet = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.RequestCapabilitiesGet.copy(block: `focstim_rpc`.RequestCapabilitiesGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.RequestCapabilitiesGet =
  `focstim_rpc`.RequestCapabilitiesGetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

