// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: focstim_rpc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerequest")
public inline fun request(block: focstim_rpc.RequestKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Request =
  focstim_rpc.RequestKt.Dsl._create(focstim_rpc.FocstimRpc.Request.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.Request`
 */
public object RequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.FocstimRpc.Request.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.FocstimRpc.Request.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.FocstimRpc.Request = _builder.build()

    /**
     * `uint32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `uint32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.RequestFirmwareVersion request_firmware_version = 500;`
     */
    public var requestFirmwareVersion: focstim_rpc.Messages.RequestFirmwareVersion
      @kotlin.jvm.JvmName("getRequestFirmwareVersion")
        get() = _builder.requestFirmwareVersion
      @kotlin.jvm.JvmName("setRequestFirmwareVersion")
        set(value) {
        _builder.requestFirmwareVersion = value
      }
    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.RequestFirmwareVersion request_firmware_version = 500;`
     */
    public fun clearRequestFirmwareVersion() {
      _builder.clearRequestFirmwareVersion()
    }
    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.RequestFirmwareVersion request_firmware_version = 500;`
     * @return Whether the requestFirmwareVersion field is set.
     */
    public fun hasRequestFirmwareVersion(): kotlin.Boolean {
      return _builder.hasRequestFirmwareVersion()
    }

    /**
     * `.focstim_rpc.RequestCapabilitiesGet request_capabilities_get = 501;`
     */
    public var requestCapabilitiesGet: focstim_rpc.Messages.RequestCapabilitiesGet
      @kotlin.jvm.JvmName("getRequestCapabilitiesGet")
        get() = _builder.requestCapabilitiesGet
      @kotlin.jvm.JvmName("setRequestCapabilitiesGet")
        set(value) {
        _builder.requestCapabilitiesGet = value
      }
    /**
     * `.focstim_rpc.RequestCapabilitiesGet request_capabilities_get = 501;`
     */
    public fun clearRequestCapabilitiesGet() {
      _builder.clearRequestCapabilitiesGet()
    }
    /**
     * `.focstim_rpc.RequestCapabilitiesGet request_capabilities_get = 501;`
     * @return Whether the requestCapabilitiesGet field is set.
     */
    public fun hasRequestCapabilitiesGet(): kotlin.Boolean {
      return _builder.hasRequestCapabilitiesGet()
    }

    /**
     * `.focstim_rpc.RequestSignalStart request_signal_start = 502;`
     */
    public var requestSignalStart: focstim_rpc.Messages.RequestSignalStart
      @kotlin.jvm.JvmName("getRequestSignalStart")
        get() = _builder.requestSignalStart
      @kotlin.jvm.JvmName("setRequestSignalStart")
        set(value) {
        _builder.requestSignalStart = value
      }
    /**
     * `.focstim_rpc.RequestSignalStart request_signal_start = 502;`
     */
    public fun clearRequestSignalStart() {
      _builder.clearRequestSignalStart()
    }
    /**
     * `.focstim_rpc.RequestSignalStart request_signal_start = 502;`
     * @return Whether the requestSignalStart field is set.
     */
    public fun hasRequestSignalStart(): kotlin.Boolean {
      return _builder.hasRequestSignalStart()
    }

    /**
     * `.focstim_rpc.RequestSignalStop request_signal_stop = 503;`
     */
    public var requestSignalStop: focstim_rpc.Messages.RequestSignalStop
      @kotlin.jvm.JvmName("getRequestSignalStop")
        get() = _builder.requestSignalStop
      @kotlin.jvm.JvmName("setRequestSignalStop")
        set(value) {
        _builder.requestSignalStop = value
      }
    /**
     * `.focstim_rpc.RequestSignalStop request_signal_stop = 503;`
     */
    public fun clearRequestSignalStop() {
      _builder.clearRequestSignalStop()
    }
    /**
     * `.focstim_rpc.RequestSignalStop request_signal_stop = 503;`
     * @return Whether the requestSignalStop field is set.
     */
    public fun hasRequestSignalStop(): kotlin.Boolean {
      return _builder.hasRequestSignalStop()
    }

    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.RequestAxisMoveTo request_axis_move_to = 5;`
     */
    public var requestAxisMoveTo: focstim_rpc.Messages.RequestAxisMoveTo
      @kotlin.jvm.JvmName("getRequestAxisMoveTo")
        get() = _builder.requestAxisMoveTo
      @kotlin.jvm.JvmName("setRequestAxisMoveTo")
        set(value) {
        _builder.requestAxisMoveTo = value
      }
    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.RequestAxisMoveTo request_axis_move_to = 5;`
     */
    public fun clearRequestAxisMoveTo() {
      _builder.clearRequestAxisMoveTo()
    }
    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.RequestAxisMoveTo request_axis_move_to = 5;`
     * @return Whether the requestAxisMoveTo field is set.
     */
    public fun hasRequestAxisMoveTo(): kotlin.Boolean {
      return _builder.hasRequestAxisMoveTo()
    }

    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.RequestTimestampSet request_timestamp_set = 504;`
     */
    public var requestTimestampSet: focstim_rpc.Messages.RequestTimestampSet
      @kotlin.jvm.JvmName("getRequestTimestampSet")
        get() = _builder.requestTimestampSet
      @kotlin.jvm.JvmName("setRequestTimestampSet")
        set(value) {
        _builder.requestTimestampSet = value
      }
    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.RequestTimestampSet request_timestamp_set = 504;`
     */
    public fun clearRequestTimestampSet() {
      _builder.clearRequestTimestampSet()
    }
    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.RequestTimestampSet request_timestamp_set = 504;`
     * @return Whether the requestTimestampSet field is set.
     */
    public fun hasRequestTimestampSet(): kotlin.Boolean {
      return _builder.hasRequestTimestampSet()
    }

    /**
     * ```
     * RequestAxisSet request_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.RequestTimestampGet request_timestamp_get = 505;`
     */
    public var requestTimestampGet: focstim_rpc.Messages.RequestTimestampGet
      @kotlin.jvm.JvmName("getRequestTimestampGet")
        get() = _builder.requestTimestampGet
      @kotlin.jvm.JvmName("setRequestTimestampGet")
        set(value) {
        _builder.requestTimestampGet = value
      }
    /**
     * ```
     * RequestAxisSet request_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.RequestTimestampGet request_timestamp_get = 505;`
     */
    public fun clearRequestTimestampGet() {
      _builder.clearRequestTimestampGet()
    }
    /**
     * ```
     * RequestAxisSet request_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.RequestTimestampGet request_timestamp_get = 505;`
     * @return Whether the requestTimestampGet field is set.
     */
    public fun hasRequestTimestampGet(): kotlin.Boolean {
      return _builder.hasRequestTimestampGet()
    }

    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.RequestWifiParametersSet request_wifi_parameters_set = 507;`
     */
    public var requestWifiParametersSet: focstim_rpc.Messages.RequestWifiParametersSet
      @kotlin.jvm.JvmName("getRequestWifiParametersSet")
        get() = _builder.requestWifiParametersSet
      @kotlin.jvm.JvmName("setRequestWifiParametersSet")
        set(value) {
        _builder.requestWifiParametersSet = value
      }
    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.RequestWifiParametersSet request_wifi_parameters_set = 507;`
     */
    public fun clearRequestWifiParametersSet() {
      _builder.clearRequestWifiParametersSet()
    }
    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.RequestWifiParametersSet request_wifi_parameters_set = 507;`
     * @return Whether the requestWifiParametersSet field is set.
     */
    public fun hasRequestWifiParametersSet(): kotlin.Boolean {
      return _builder.hasRequestWifiParametersSet()
    }

    /**
     * `.focstim_rpc.RequestWifiIPGet request_wifi_ip_get = 508;`
     */
    public var requestWifiIpGet: focstim_rpc.Messages.RequestWifiIPGet
      @kotlin.jvm.JvmName("getRequestWifiIpGet")
        get() = _builder.requestWifiIpGet
      @kotlin.jvm.JvmName("setRequestWifiIpGet")
        set(value) {
        _builder.requestWifiIpGet = value
      }
    /**
     * `.focstim_rpc.RequestWifiIPGet request_wifi_ip_get = 508;`
     */
    public fun clearRequestWifiIpGet() {
      _builder.clearRequestWifiIpGet()
    }
    /**
     * `.focstim_rpc.RequestWifiIPGet request_wifi_ip_get = 508;`
     * @return Whether the requestWifiIpGet field is set.
     */
    public fun hasRequestWifiIpGet(): kotlin.Boolean {
      return _builder.hasRequestWifiIpGet()
    }

    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.RequestLockDeviceVolume request_lock_device_volume = 509;`
     */
    public var requestLockDeviceVolume: focstim_rpc.Messages.RequestLockDeviceVolume
      @kotlin.jvm.JvmName("getRequestLockDeviceVolume")
        get() = _builder.requestLockDeviceVolume
      @kotlin.jvm.JvmName("setRequestLockDeviceVolume")
        set(value) {
        _builder.requestLockDeviceVolume = value
      }
    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.RequestLockDeviceVolume request_lock_device_volume = 509;`
     */
    public fun clearRequestLockDeviceVolume() {
      _builder.clearRequestLockDeviceVolume()
    }
    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.RequestLockDeviceVolume request_lock_device_volume = 509;`
     * @return Whether the requestLockDeviceVolume field is set.
     */
    public fun hasRequestLockDeviceVolume(): kotlin.Boolean {
      return _builder.hasRequestLockDeviceVolume()
    }

    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.RequestLSM6DSOXStart request_lsm6dsox_start = 600;`
     */
    public var requestLsm6DsoxStart: focstim_rpc.Messages.RequestLSM6DSOXStart
      @kotlin.jvm.JvmName("getRequestLsm6DsoxStart")
        get() = _builder.requestLsm6DsoxStart
      @kotlin.jvm.JvmName("setRequestLsm6DsoxStart")
        set(value) {
        _builder.requestLsm6DsoxStart = value
      }
    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.RequestLSM6DSOXStart request_lsm6dsox_start = 600;`
     */
    public fun clearRequestLsm6DsoxStart() {
      _builder.clearRequestLsm6DsoxStart()
    }
    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.RequestLSM6DSOXStart request_lsm6dsox_start = 600;`
     * @return Whether the requestLsm6dsoxStart field is set.
     */
    public fun hasRequestLsm6DsoxStart(): kotlin.Boolean {
      return _builder.hasRequestLsm6DsoxStart()
    }

    /**
     * `.focstim_rpc.RequestLSM6DSOXStop request_lsm6dsox_stop = 601;`
     */
    public var requestLsm6DsoxStop: focstim_rpc.Messages.RequestLSM6DSOXStop
      @kotlin.jvm.JvmName("getRequestLsm6DsoxStop")
        get() = _builder.requestLsm6DsoxStop
      @kotlin.jvm.JvmName("setRequestLsm6DsoxStop")
        set(value) {
        _builder.requestLsm6DsoxStop = value
      }
    /**
     * `.focstim_rpc.RequestLSM6DSOXStop request_lsm6dsox_stop = 601;`
     */
    public fun clearRequestLsm6DsoxStop() {
      _builder.clearRequestLsm6DsoxStop()
    }
    /**
     * `.focstim_rpc.RequestLSM6DSOXStop request_lsm6dsox_stop = 601;`
     * @return Whether the requestLsm6dsoxStop field is set.
     */
    public fun hasRequestLsm6DsoxStop(): kotlin.Boolean {
      return _builder.hasRequestLsm6DsoxStop()
    }

    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.RequestDebugStm32DeepSleep request_debug_stm32_deep_sleep = 1000;`
     */
    public var requestDebugStm32DeepSleep: focstim_rpc.Messages.RequestDebugStm32DeepSleep
      @kotlin.jvm.JvmName("getRequestDebugStm32DeepSleep")
        get() = _builder.requestDebugStm32DeepSleep
      @kotlin.jvm.JvmName("setRequestDebugStm32DeepSleep")
        set(value) {
        _builder.requestDebugStm32DeepSleep = value
      }
    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.RequestDebugStm32DeepSleep request_debug_stm32_deep_sleep = 1000;`
     */
    public fun clearRequestDebugStm32DeepSleep() {
      _builder.clearRequestDebugStm32DeepSleep()
    }
    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.RequestDebugStm32DeepSleep request_debug_stm32_deep_sleep = 1000;`
     * @return Whether the requestDebugStm32DeepSleep field is set.
     */
    public fun hasRequestDebugStm32DeepSleep(): kotlin.Boolean {
      return _builder.hasRequestDebugStm32DeepSleep()
    }

    /**
     * `.focstim_rpc.RequestDebugEnterBootloader request_debug_enter_bootloader = 1001;`
     */
    public var requestDebugEnterBootloader: focstim_rpc.Messages.RequestDebugEnterBootloader
      @kotlin.jvm.JvmName("getRequestDebugEnterBootloader")
        get() = _builder.requestDebugEnterBootloader
      @kotlin.jvm.JvmName("setRequestDebugEnterBootloader")
        set(value) {
        _builder.requestDebugEnterBootloader = value
      }
    /**
     * `.focstim_rpc.RequestDebugEnterBootloader request_debug_enter_bootloader = 1001;`
     */
    public fun clearRequestDebugEnterBootloader() {
      _builder.clearRequestDebugEnterBootloader()
    }
    /**
     * `.focstim_rpc.RequestDebugEnterBootloader request_debug_enter_bootloader = 1001;`
     * @return Whether the requestDebugEnterBootloader field is set.
     */
    public fun hasRequestDebugEnterBootloader(): kotlin.Boolean {
      return _builder.hasRequestDebugEnterBootloader()
    }
    public val paramsCase: focstim_rpc.FocstimRpc.Request.ParamsCase
    @kotlin.jvm.JvmName("getParamsCase")
      get() = _builder.getParamsCase()

    public fun clearParams() {
      _builder.clearParams()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.FocstimRpc.Request.copy(block: `focstim_rpc`.RequestKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Request =
  `focstim_rpc`.RequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestFirmwareVersionOrNull: focstim_rpc.Messages.RequestFirmwareVersion?
  get() = if (hasRequestFirmwareVersion()) getRequestFirmwareVersion() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestCapabilitiesGetOrNull: focstim_rpc.Messages.RequestCapabilitiesGet?
  get() = if (hasRequestCapabilitiesGet()) getRequestCapabilitiesGet() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestSignalStartOrNull: focstim_rpc.Messages.RequestSignalStart?
  get() = if (hasRequestSignalStart()) getRequestSignalStart() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestSignalStopOrNull: focstim_rpc.Messages.RequestSignalStop?
  get() = if (hasRequestSignalStop()) getRequestSignalStop() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestAxisMoveToOrNull: focstim_rpc.Messages.RequestAxisMoveTo?
  get() = if (hasRequestAxisMoveTo()) getRequestAxisMoveTo() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestTimestampSetOrNull: focstim_rpc.Messages.RequestTimestampSet?
  get() = if (hasRequestTimestampSet()) getRequestTimestampSet() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestTimestampGetOrNull: focstim_rpc.Messages.RequestTimestampGet?
  get() = if (hasRequestTimestampGet()) getRequestTimestampGet() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestWifiParametersSetOrNull: focstim_rpc.Messages.RequestWifiParametersSet?
  get() = if (hasRequestWifiParametersSet()) getRequestWifiParametersSet() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestWifiIpGetOrNull: focstim_rpc.Messages.RequestWifiIPGet?
  get() = if (hasRequestWifiIpGet()) getRequestWifiIpGet() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestLockDeviceVolumeOrNull: focstim_rpc.Messages.RequestLockDeviceVolume?
  get() = if (hasRequestLockDeviceVolume()) getRequestLockDeviceVolume() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestLsm6DsoxStartOrNull: focstim_rpc.Messages.RequestLSM6DSOXStart?
  get() = if (hasRequestLsm6DsoxStart()) getRequestLsm6DsoxStart() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestLsm6DsoxStopOrNull: focstim_rpc.Messages.RequestLSM6DSOXStop?
  get() = if (hasRequestLsm6DsoxStop()) getRequestLsm6DsoxStop() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestDebugStm32DeepSleepOrNull: focstim_rpc.Messages.RequestDebugStm32DeepSleep?
  get() = if (hasRequestDebugStm32DeepSleep()) getRequestDebugStm32DeepSleep() else null

public val focstim_rpc.FocstimRpc.RequestOrBuilder.requestDebugEnterBootloaderOrNull: focstim_rpc.Messages.RequestDebugEnterBootloader?
  get() = if (hasRequestDebugEnterBootloader()) getRequestDebugEnterBootloader() else null

