// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseLSM6DSOXStop")
public inline fun responseLSM6DSOXStop(block: focstim_rpc.ResponseLSM6DSOXStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLSM6DSOXStop =
  focstim_rpc.ResponseLSM6DSOXStopKt.Dsl._create(focstim_rpc.Messages.ResponseLSM6DSOXStop.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseLSM6DSOXStop`
 */
public object ResponseLSM6DSOXStopKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseLSM6DSOXStop.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseLSM6DSOXStop.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseLSM6DSOXStop = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseLSM6DSOXStop.copy(block: `focstim_rpc`.ResponseLSM6DSOXStopKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLSM6DSOXStop =
  `focstim_rpc`.ResponseLSM6DSOXStopKt.Dsl._create(this.toBuilder()).apply { block() }._build()

