// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseLockDeviceVolume")
public inline fun responseLockDeviceVolume(block: focstim_rpc.ResponseLockDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLockDeviceVolume =
  focstim_rpc.ResponseLockDeviceVolumeKt.Dsl._create(focstim_rpc.Messages.ResponseLockDeviceVolume.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseLockDeviceVolume`
 */
public object ResponseLockDeviceVolumeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseLockDeviceVolume.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseLockDeviceVolume.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseLockDeviceVolume = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseLockDeviceVolume.copy(block: `focstim_rpc`.ResponseLockDeviceVolumeKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLockDeviceVolume =
  `focstim_rpc`.ResponseLockDeviceVolumeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

