// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseTimestampGet")
public inline fun responseTimestampGet(block: focstim_rpc.ResponseTimestampGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseTimestampGet =
  focstim_rpc.ResponseTimestampGetKt.Dsl._create(focstim_rpc.Messages.ResponseTimestampGet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseTimestampGet`
 */
public object ResponseTimestampGetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseTimestampGet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseTimestampGet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseTimestampGet = _builder.build()

    /**
     * ```
     * local clock, uint32_t on system.
     * ```
     *
     * `fixed32 timestamp_ms = 1;`
     */
    public var timestampMs: kotlin.Int
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * ```
     * local clock, uint32_t on system.
     * ```
     *
     * `fixed32 timestamp_ms = 1;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }

    /**
     * ```
     * synchronized clock
     * ```
     *
     * `uint64 unix_timestamp_ms = 2;`
     */
    public var unixTimestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getUnixTimestampMs")
        get() = _builder.unixTimestampMs
      @kotlin.jvm.JvmName("setUnixTimestampMs")
        set(value) {
        _builder.unixTimestampMs = value
      }
    /**
     * ```
     * synchronized clock
     * ```
     *
     * `uint64 unix_timestamp_ms = 2;`
     */
    public fun clearUnixTimestampMs() {
      _builder.clearUnixTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseTimestampGet.copy(block: `focstim_rpc`.ResponseTimestampGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseTimestampGet =
  `focstim_rpc`.ResponseTimestampGetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

