// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseLSM6DSOXStart")
public inline fun responseLSM6DSOXStart(block: focstim_rpc.ResponseLSM6DSOXStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLSM6DSOXStart =
  focstim_rpc.ResponseLSM6DSOXStartKt.Dsl._create(focstim_rpc.Messages.ResponseLSM6DSOXStart.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseLSM6DSOXStart`
 */
public object ResponseLSM6DSOXStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseLSM6DSOXStart.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseLSM6DSOXStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseLSM6DSOXStart = _builder.build()

    /**
     * ```
     * conversion factor from readings to mili-g
     * ```
     *
     * `float acc_sensitivity = 1;`
     */
    public var accSensitivity: kotlin.Float
      @kotlin.jvm.JvmName("getAccSensitivity")
        get() = _builder.accSensitivity
      @kotlin.jvm.JvmName("setAccSensitivity")
        set(value) {
        _builder.accSensitivity = value
      }
    /**
     * ```
     * conversion factor from readings to mili-g
     * ```
     *
     * `float acc_sensitivity = 1;`
     */
    public fun clearAccSensitivity() {
      _builder.clearAccSensitivity()
    }

    /**
     * ```
     * conversion factor from readings to mili-degrees-per-second
     * ```
     *
     * `float gyr_sensitivity = 2;`
     */
    public var gyrSensitivity: kotlin.Float
      @kotlin.jvm.JvmName("getGyrSensitivity")
        get() = _builder.gyrSensitivity
      @kotlin.jvm.JvmName("setGyrSensitivity")
        set(value) {
        _builder.gyrSensitivity = value
      }
    /**
     * ```
     * conversion factor from readings to mili-degrees-per-second
     * ```
     *
     * `float gyr_sensitivity = 2;`
     */
    public fun clearGyrSensitivity() {
      _builder.clearGyrSensitivity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseLSM6DSOXStart.copy(block: `focstim_rpc`.ResponseLSM6DSOXStartKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseLSM6DSOXStart =
  `focstim_rpc`.ResponseLSM6DSOXStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

