// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseAxisSet")
public inline fun responseAxisSet(block: focstim_rpc.ResponseAxisSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseAxisSet =
  focstim_rpc.ResponseAxisSetKt.Dsl._create(focstim_rpc.Messages.ResponseAxisSet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseAxisSet`
 */
public object ResponseAxisSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseAxisSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseAxisSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseAxisSet = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseAxisSet.copy(block: `focstim_rpc`.ResponseAxisSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseAxisSet =
  `focstim_rpc`.ResponseAxisSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

