// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: focstim_rpc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponse")
public inline fun response(block: focstim_rpc.ResponseKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Response =
  focstim_rpc.ResponseKt.Dsl._create(focstim_rpc.FocstimRpc.Response.newBuilder()).apply { block() }._build()
/**
 * ```
 * Responses have the same ID as the request. NB! not all requests will have a result, and just return a blank response
 * ```
 *
 * Protobuf type `focstim_rpc.Response`
 */
public object ResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.FocstimRpc.Response.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.FocstimRpc.Response.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.FocstimRpc.Response = _builder.build()

    /**
     * `uint32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `uint32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.ResponseFirmwareVersion response_firmware_version = 500;`
     */
    public var responseFirmwareVersion: focstim_rpc.Messages.ResponseFirmwareVersion
      @kotlin.jvm.JvmName("getResponseFirmwareVersion")
        get() = _builder.responseFirmwareVersion
      @kotlin.jvm.JvmName("setResponseFirmwareVersion")
        set(value) {
        _builder.responseFirmwareVersion = value
      }
    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.ResponseFirmwareVersion response_firmware_version = 500;`
     */
    public fun clearResponseFirmwareVersion() {
      _builder.clearResponseFirmwareVersion()
    }
    /**
     * ```
     * general commands
     * ```
     *
     * `.focstim_rpc.ResponseFirmwareVersion response_firmware_version = 500;`
     * @return Whether the responseFirmwareVersion field is set.
     */
    public fun hasResponseFirmwareVersion(): kotlin.Boolean {
      return _builder.hasResponseFirmwareVersion()
    }

    /**
     * `.focstim_rpc.ResponseCapabilitiesGet response_capabilities_get = 501;`
     */
    public var responseCapabilitiesGet: focstim_rpc.Messages.ResponseCapabilitiesGet
      @kotlin.jvm.JvmName("getResponseCapabilitiesGet")
        get() = _builder.responseCapabilitiesGet
      @kotlin.jvm.JvmName("setResponseCapabilitiesGet")
        set(value) {
        _builder.responseCapabilitiesGet = value
      }
    /**
     * `.focstim_rpc.ResponseCapabilitiesGet response_capabilities_get = 501;`
     */
    public fun clearResponseCapabilitiesGet() {
      _builder.clearResponseCapabilitiesGet()
    }
    /**
     * `.focstim_rpc.ResponseCapabilitiesGet response_capabilities_get = 501;`
     * @return Whether the responseCapabilitiesGet field is set.
     */
    public fun hasResponseCapabilitiesGet(): kotlin.Boolean {
      return _builder.hasResponseCapabilitiesGet()
    }

    /**
     * `.focstim_rpc.ResponseSignalStart response_signal_start = 502;`
     */
    public var responseSignalStart: focstim_rpc.Messages.ResponseSignalStart
      @kotlin.jvm.JvmName("getResponseSignalStart")
        get() = _builder.responseSignalStart
      @kotlin.jvm.JvmName("setResponseSignalStart")
        set(value) {
        _builder.responseSignalStart = value
      }
    /**
     * `.focstim_rpc.ResponseSignalStart response_signal_start = 502;`
     */
    public fun clearResponseSignalStart() {
      _builder.clearResponseSignalStart()
    }
    /**
     * `.focstim_rpc.ResponseSignalStart response_signal_start = 502;`
     * @return Whether the responseSignalStart field is set.
     */
    public fun hasResponseSignalStart(): kotlin.Boolean {
      return _builder.hasResponseSignalStart()
    }

    /**
     * `.focstim_rpc.ResponseSignalStop response_signal_stop = 503;`
     */
    public var responseSignalStop: focstim_rpc.Messages.ResponseSignalStop
      @kotlin.jvm.JvmName("getResponseSignalStop")
        get() = _builder.responseSignalStop
      @kotlin.jvm.JvmName("setResponseSignalStop")
        set(value) {
        _builder.responseSignalStop = value
      }
    /**
     * `.focstim_rpc.ResponseSignalStop response_signal_stop = 503;`
     */
    public fun clearResponseSignalStop() {
      _builder.clearResponseSignalStop()
    }
    /**
     * `.focstim_rpc.ResponseSignalStop response_signal_stop = 503;`
     * @return Whether the responseSignalStop field is set.
     */
    public fun hasResponseSignalStop(): kotlin.Boolean {
      return _builder.hasResponseSignalStop()
    }

    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.ResponseAxisMoveTo response_axis_move_to = 5;`
     */
    public var responseAxisMoveTo: focstim_rpc.Messages.ResponseAxisMoveTo
      @kotlin.jvm.JvmName("getResponseAxisMoveTo")
        get() = _builder.responseAxisMoveTo
      @kotlin.jvm.JvmName("setResponseAxisMoveTo")
        set(value) {
        _builder.responseAxisMoveTo = value
      }
    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.ResponseAxisMoveTo response_axis_move_to = 5;`
     */
    public fun clearResponseAxisMoveTo() {
      _builder.clearResponseAxisMoveTo()
    }
    /**
     * ```
     * MoveTo streaming API
     * ```
     *
     * `.focstim_rpc.ResponseAxisMoveTo response_axis_move_to = 5;`
     * @return Whether the responseAxisMoveTo field is set.
     */
    public fun hasResponseAxisMoveTo(): kotlin.Boolean {
      return _builder.hasResponseAxisMoveTo()
    }

    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.ResponseTimestampSet response_timestamp_set = 504;`
     */
    public var responseTimestampSet: focstim_rpc.Messages.ResponseTimestampSet
      @kotlin.jvm.JvmName("getResponseTimestampSet")
        get() = _builder.responseTimestampSet
      @kotlin.jvm.JvmName("setResponseTimestampSet")
        set(value) {
        _builder.responseTimestampSet = value
      }
    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.ResponseTimestampSet response_timestamp_set = 504;`
     */
    public fun clearResponseTimestampSet() {
      _builder.clearResponseTimestampSet()
    }
    /**
     * ```
     * Buffered streaming API -- not yet implemented
     * ```
     *
     * `.focstim_rpc.ResponseTimestampSet response_timestamp_set = 504;`
     * @return Whether the responseTimestampSet field is set.
     */
    public fun hasResponseTimestampSet(): kotlin.Boolean {
      return _builder.hasResponseTimestampSet()
    }

    /**
     * ```
     * ResponseAxisSet response_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.ResponseTimestampGet response_timestamp_get = 505;`
     */
    public var responseTimestampGet: focstim_rpc.Messages.ResponseTimestampGet
      @kotlin.jvm.JvmName("getResponseTimestampGet")
        get() = _builder.responseTimestampGet
      @kotlin.jvm.JvmName("setResponseTimestampGet")
        set(value) {
        _builder.responseTimestampGet = value
      }
    /**
     * ```
     * ResponseAxisSet response_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.ResponseTimestampGet response_timestamp_get = 505;`
     */
    public fun clearResponseTimestampGet() {
      _builder.clearResponseTimestampGet()
    }
    /**
     * ```
     * ResponseAxisSet response_axis_set = 506;
     * ```
     *
     * `.focstim_rpc.ResponseTimestampGet response_timestamp_get = 505;`
     * @return Whether the responseTimestampGet field is set.
     */
    public fun hasResponseTimestampGet(): kotlin.Boolean {
      return _builder.hasResponseTimestampGet()
    }

    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.ResponseWifiParametersSet response_wifi_parameters_set = 507;`
     */
    public var responseWifiParametersSet: focstim_rpc.Messages.ResponseWifiParametersSet
      @kotlin.jvm.JvmName("getResponseWifiParametersSet")
        get() = _builder.responseWifiParametersSet
      @kotlin.jvm.JvmName("setResponseWifiParametersSet")
        set(value) {
        _builder.responseWifiParametersSet = value
      }
    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.ResponseWifiParametersSet response_wifi_parameters_set = 507;`
     */
    public fun clearResponseWifiParametersSet() {
      _builder.clearResponseWifiParametersSet()
    }
    /**
     * ```
     * network
     * ```
     *
     * `.focstim_rpc.ResponseWifiParametersSet response_wifi_parameters_set = 507;`
     * @return Whether the responseWifiParametersSet field is set.
     */
    public fun hasResponseWifiParametersSet(): kotlin.Boolean {
      return _builder.hasResponseWifiParametersSet()
    }

    /**
     * `.focstim_rpc.ResponseWifiIPGet response_wifi_ip_get = 508;`
     */
    public var responseWifiIpGet: focstim_rpc.Messages.ResponseWifiIPGet
      @kotlin.jvm.JvmName("getResponseWifiIpGet")
        get() = _builder.responseWifiIpGet
      @kotlin.jvm.JvmName("setResponseWifiIpGet")
        set(value) {
        _builder.responseWifiIpGet = value
      }
    /**
     * `.focstim_rpc.ResponseWifiIPGet response_wifi_ip_get = 508;`
     */
    public fun clearResponseWifiIpGet() {
      _builder.clearResponseWifiIpGet()
    }
    /**
     * `.focstim_rpc.ResponseWifiIPGet response_wifi_ip_get = 508;`
     * @return Whether the responseWifiIpGet field is set.
     */
    public fun hasResponseWifiIpGet(): kotlin.Boolean {
      return _builder.hasResponseWifiIpGet()
    }

    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.ResponseLockDeviceVolume response_lock_device_volume = 509;`
     */
    public var responseLockDeviceVolume: focstim_rpc.Messages.ResponseLockDeviceVolume
      @kotlin.jvm.JvmName("getResponseLockDeviceVolume")
        get() = _builder.responseLockDeviceVolume
      @kotlin.jvm.JvmName("setResponseLockDeviceVolume")
        set(value) {
        _builder.responseLockDeviceVolume = value
      }
    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.ResponseLockDeviceVolume response_lock_device_volume = 509;`
     */
    public fun clearResponseLockDeviceVolume() {
      _builder.clearResponseLockDeviceVolume()
    }
    /**
     * ```
     * device volume lock
     * ```
     *
     * `.focstim_rpc.ResponseLockDeviceVolume response_lock_device_volume = 509;`
     * @return Whether the responseLockDeviceVolume field is set.
     */
    public fun hasResponseLockDeviceVolume(): kotlin.Boolean {
      return _builder.hasResponseLockDeviceVolume()
    }

    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.ResponseLSM6DSOXStart response_lsm6dsox_start = 600;`
     */
    public var responseLsm6DsoxStart: focstim_rpc.Messages.ResponseLSM6DSOXStart
      @kotlin.jvm.JvmName("getResponseLsm6DsoxStart")
        get() = _builder.responseLsm6DsoxStart
      @kotlin.jvm.JvmName("setResponseLsm6DsoxStart")
        set(value) {
        _builder.responseLsm6DsoxStart = value
      }
    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.ResponseLSM6DSOXStart response_lsm6dsox_start = 600;`
     */
    public fun clearResponseLsm6DsoxStart() {
      _builder.clearResponseLsm6DsoxStart()
    }
    /**
     * ```
     * sensors
     * ```
     *
     * `.focstim_rpc.ResponseLSM6DSOXStart response_lsm6dsox_start = 600;`
     * @return Whether the responseLsm6dsoxStart field is set.
     */
    public fun hasResponseLsm6DsoxStart(): kotlin.Boolean {
      return _builder.hasResponseLsm6DsoxStart()
    }

    /**
     * `.focstim_rpc.ResponseLSM6DSOXStop response_lsm6dsox_stop = 601;`
     */
    public var responseLsm6DsoxStop: focstim_rpc.Messages.ResponseLSM6DSOXStop
      @kotlin.jvm.JvmName("getResponseLsm6DsoxStop")
        get() = _builder.responseLsm6DsoxStop
      @kotlin.jvm.JvmName("setResponseLsm6DsoxStop")
        set(value) {
        _builder.responseLsm6DsoxStop = value
      }
    /**
     * `.focstim_rpc.ResponseLSM6DSOXStop response_lsm6dsox_stop = 601;`
     */
    public fun clearResponseLsm6DsoxStop() {
      _builder.clearResponseLsm6DsoxStop()
    }
    /**
     * `.focstim_rpc.ResponseLSM6DSOXStop response_lsm6dsox_stop = 601;`
     * @return Whether the responseLsm6dsoxStop field is set.
     */
    public fun hasResponseLsm6DsoxStop(): kotlin.Boolean {
      return _builder.hasResponseLsm6DsoxStop()
    }

    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.ResponseDebugStm32DeepSleep response_debug_stm32_deep_sleep = 1000;`
     */
    public var responseDebugStm32DeepSleep: focstim_rpc.Messages.ResponseDebugStm32DeepSleep
      @kotlin.jvm.JvmName("getResponseDebugStm32DeepSleep")
        get() = _builder.responseDebugStm32DeepSleep
      @kotlin.jvm.JvmName("setResponseDebugStm32DeepSleep")
        set(value) {
        _builder.responseDebugStm32DeepSleep = value
      }
    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.ResponseDebugStm32DeepSleep response_debug_stm32_deep_sleep = 1000;`
     */
    public fun clearResponseDebugStm32DeepSleep() {
      _builder.clearResponseDebugStm32DeepSleep()
    }
    /**
     * ```
     * debug
     * ```
     *
     * `.focstim_rpc.ResponseDebugStm32DeepSleep response_debug_stm32_deep_sleep = 1000;`
     * @return Whether the responseDebugStm32DeepSleep field is set.
     */
    public fun hasResponseDebugStm32DeepSleep(): kotlin.Boolean {
      return _builder.hasResponseDebugStm32DeepSleep()
    }

    /**
     * ```
     * Transportation transport = 3; //optional - internal use only
     * ```
     *
     * `.focstim_rpc.Error error = 3;`
     */
    public var error: focstim_rpc.FocstimRpc.Error
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * ```
     * Transportation transport = 3; //optional - internal use only
     * ```
     *
     * `.focstim_rpc.Error error = 3;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * ```
     * Transportation transport = 3; //optional - internal use only
     * ```
     *
     * `.focstim_rpc.Error error = 3;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val ResponseKt.Dsl.errorOrNull: focstim_rpc.FocstimRpc.Error?
      get() = _builder.errorOrNull
    public val resultCase: focstim_rpc.FocstimRpc.Response.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.FocstimRpc.Response.copy(block: `focstim_rpc`.ResponseKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.Response =
  `focstim_rpc`.ResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseFirmwareVersionOrNull: focstim_rpc.Messages.ResponseFirmwareVersion?
  get() = if (hasResponseFirmwareVersion()) getResponseFirmwareVersion() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseCapabilitiesGetOrNull: focstim_rpc.Messages.ResponseCapabilitiesGet?
  get() = if (hasResponseCapabilitiesGet()) getResponseCapabilitiesGet() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseSignalStartOrNull: focstim_rpc.Messages.ResponseSignalStart?
  get() = if (hasResponseSignalStart()) getResponseSignalStart() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseSignalStopOrNull: focstim_rpc.Messages.ResponseSignalStop?
  get() = if (hasResponseSignalStop()) getResponseSignalStop() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseAxisMoveToOrNull: focstim_rpc.Messages.ResponseAxisMoveTo?
  get() = if (hasResponseAxisMoveTo()) getResponseAxisMoveTo() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseTimestampSetOrNull: focstim_rpc.Messages.ResponseTimestampSet?
  get() = if (hasResponseTimestampSet()) getResponseTimestampSet() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseTimestampGetOrNull: focstim_rpc.Messages.ResponseTimestampGet?
  get() = if (hasResponseTimestampGet()) getResponseTimestampGet() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseWifiParametersSetOrNull: focstim_rpc.Messages.ResponseWifiParametersSet?
  get() = if (hasResponseWifiParametersSet()) getResponseWifiParametersSet() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseWifiIpGetOrNull: focstim_rpc.Messages.ResponseWifiIPGet?
  get() = if (hasResponseWifiIpGet()) getResponseWifiIpGet() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseLockDeviceVolumeOrNull: focstim_rpc.Messages.ResponseLockDeviceVolume?
  get() = if (hasResponseLockDeviceVolume()) getResponseLockDeviceVolume() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseLsm6DsoxStartOrNull: focstim_rpc.Messages.ResponseLSM6DSOXStart?
  get() = if (hasResponseLsm6DsoxStart()) getResponseLsm6DsoxStart() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseLsm6DsoxStopOrNull: focstim_rpc.Messages.ResponseLSM6DSOXStop?
  get() = if (hasResponseLsm6DsoxStop()) getResponseLsm6DsoxStop() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.responseDebugStm32DeepSleepOrNull: focstim_rpc.Messages.ResponseDebugStm32DeepSleep?
  get() = if (hasResponseDebugStm32DeepSleep()) getResponseDebugStm32DeepSleep() else null

public val focstim_rpc.FocstimRpc.ResponseOrBuilder.errorOrNull: focstim_rpc.FocstimRpc.Error?
  get() = if (hasError()) getError() else null

