// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseWifiIPGet")
public inline fun responseWifiIPGet(block: focstim_rpc.ResponseWifiIPGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseWifiIPGet =
  focstim_rpc.ResponseWifiIPGetKt.Dsl._create(focstim_rpc.Messages.ResponseWifiIPGet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseWifiIPGet`
 */
public object ResponseWifiIPGetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseWifiIPGet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseWifiIPGet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseWifiIPGet = _builder.build()

    /**
     * `uint32 ip = 1;`
     */
    public var ip: kotlin.Int
      @kotlin.jvm.JvmName("getIp")
        get() = _builder.ip
      @kotlin.jvm.JvmName("setIp")
        set(value) {
        _builder.ip = value
      }
    /**
     * `uint32 ip = 1;`
     */
    public fun clearIp() {
      _builder.clearIp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseWifiIPGet.copy(block: `focstim_rpc`.ResponseWifiIPGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseWifiIPGet =
  `focstim_rpc`.ResponseWifiIPGetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

