// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseTimestampSet")
public inline fun responseTimestampSet(block: focstim_rpc.ResponseTimestampSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseTimestampSet =
  focstim_rpc.ResponseTimestampSetKt.Dsl._create(focstim_rpc.Messages.ResponseTimestampSet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseTimestampSet`
 */
public object ResponseTimestampSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseTimestampSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseTimestampSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseTimestampSet = _builder.build()

    /**
     * ```
     * new offset between epoch and local system clock
     * ```
     *
     * `int64 offset_ms = 1;`
     */
    public var offsetMs: kotlin.Long
      @kotlin.jvm.JvmName("getOffsetMs")
        get() = _builder.offsetMs
      @kotlin.jvm.JvmName("setOffsetMs")
        set(value) {
        _builder.offsetMs = value
      }
    /**
     * ```
     * new offset between epoch and local system clock
     * ```
     *
     * `int64 offset_ms = 1;`
     */
    public fun clearOffsetMs() {
      _builder.clearOffsetMs()
    }

    /**
     * ```
     * how much the offset changed in the operation
     * ```
     *
     * `sint64 change_ms = 2;`
     */
    public var changeMs: kotlin.Long
      @kotlin.jvm.JvmName("getChangeMs")
        get() = _builder.changeMs
      @kotlin.jvm.JvmName("setChangeMs")
        set(value) {
        _builder.changeMs = value
      }
    /**
     * ```
     * how much the offset changed in the operation
     * ```
     *
     * `sint64 change_ms = 2;`
     */
    public fun clearChangeMs() {
      _builder.clearChangeMs()
    }

    /**
     * ```
     * the error between
     * ```
     *
     * `sint64 error_ms = 3;`
     */
    public var errorMs: kotlin.Long
      @kotlin.jvm.JvmName("getErrorMs")
        get() = _builder.errorMs
      @kotlin.jvm.JvmName("setErrorMs")
        set(value) {
        _builder.errorMs = value
      }
    /**
     * ```
     * the error between
     * ```
     *
     * `sint64 error_ms = 3;`
     */
    public fun clearErrorMs() {
      _builder.clearErrorMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseTimestampSet.copy(block: `focstim_rpc`.ResponseTimestampSetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseTimestampSet =
  `focstim_rpc`.ResponseTimestampSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

