// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseCapabilitiesGet")
public inline fun responseCapabilitiesGet(block: focstim_rpc.ResponseCapabilitiesGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseCapabilitiesGet =
  focstim_rpc.ResponseCapabilitiesGetKt.Dsl._create(focstim_rpc.Messages.ResponseCapabilitiesGet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseCapabilitiesGet`
 */
public object ResponseCapabilitiesGetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseCapabilitiesGet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseCapabilitiesGet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseCapabilitiesGet = _builder.build()

    /**
     * `bool threephase = 1;`
     */
    public var threephase: kotlin.Boolean
      @kotlin.jvm.JvmName("getThreephase")
        get() = _builder.threephase
      @kotlin.jvm.JvmName("setThreephase")
        set(value) {
        _builder.threephase = value
      }
    /**
     * `bool threephase = 1;`
     */
    public fun clearThreephase() {
      _builder.clearThreephase()
    }

    /**
     * `bool fourphase = 2;`
     */
    public var fourphase: kotlin.Boolean
      @kotlin.jvm.JvmName("getFourphase")
        get() = _builder.fourphase
      @kotlin.jvm.JvmName("setFourphase")
        set(value) {
        _builder.fourphase = value
      }
    /**
     * `bool fourphase = 2;`
     */
    public fun clearFourphase() {
      _builder.clearFourphase()
    }

    /**
     * ```
     * true if device has a battery installed
     * ```
     *
     * `bool battery = 3;`
     */
    public var battery: kotlin.Boolean
      @kotlin.jvm.JvmName("getBattery")
        get() = _builder.battery
      @kotlin.jvm.JvmName("setBattery")
        set(value) {
        _builder.battery = value
      }
    /**
     * ```
     * true if device has a battery installed
     * ```
     *
     * `bool battery = 3;`
     */
    public fun clearBattery() {
      _builder.clearBattery()
    }

    /**
     * `bool device_volume = 4;`
     */
    public var deviceVolume: kotlin.Boolean
      @kotlin.jvm.JvmName("getDeviceVolume")
        get() = _builder.deviceVolume
      @kotlin.jvm.JvmName("setDeviceVolume")
        set(value) {
        _builder.deviceVolume = value
      }
    /**
     * `bool device_volume = 4;`
     */
    public fun clearDeviceVolume() {
      _builder.clearDeviceVolume()
    }

    /**
     * `float maximum_waveform_amplitude_amps = 5;`
     */
    public var maximumWaveformAmplitudeAmps: kotlin.Float
      @kotlin.jvm.JvmName("getMaximumWaveformAmplitudeAmps")
        get() = _builder.maximumWaveformAmplitudeAmps
      @kotlin.jvm.JvmName("setMaximumWaveformAmplitudeAmps")
        set(value) {
        _builder.maximumWaveformAmplitudeAmps = value
      }
    /**
     * `float maximum_waveform_amplitude_amps = 5;`
     */
    public fun clearMaximumWaveformAmplitudeAmps() {
      _builder.clearMaximumWaveformAmplitudeAmps()
    }

    /**
     * `bool lsm6dsox = 6;`
     */
    public var lsm6Dsox: kotlin.Boolean
      @kotlin.jvm.JvmName("getLsm6Dsox")
        get() = _builder.lsm6Dsox
      @kotlin.jvm.JvmName("setLsm6Dsox")
        set(value) {
        _builder.lsm6Dsox = value
      }
    /**
     * `bool lsm6dsox = 6;`
     */
    public fun clearLsm6Dsox() {
      _builder.clearLsm6Dsox()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseCapabilitiesGet.copy(block: `focstim_rpc`.ResponseCapabilitiesGetKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseCapabilitiesGet =
  `focstim_rpc`.ResponseCapabilitiesGetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

