// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseFirmwareVersion")
public inline fun responseFirmwareVersion(block: focstim_rpc.ResponseFirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseFirmwareVersion =
  focstim_rpc.ResponseFirmwareVersionKt.Dsl._create(focstim_rpc.Messages.ResponseFirmwareVersion.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseFirmwareVersion`
 */
public object ResponseFirmwareVersionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseFirmwareVersion.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseFirmwareVersion.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseFirmwareVersion = _builder.build()

    /**
     * ```
     * string stm32_firmware_version = 2;  // DEPRECATED
     * ```
     *
     * `.focstim_rpc.BoardIdentifier board = 1;`
     */
    public var board: focstim_rpc.Constants.BoardIdentifier
      @kotlin.jvm.JvmName("getBoard")
        get() = _builder.board
      @kotlin.jvm.JvmName("setBoard")
        set(value) {
        _builder.board = value
      }
    public var boardValue: kotlin.Int
      @kotlin.jvm.JvmName("getBoardValue")
        get() = _builder.boardValue
      @kotlin.jvm.JvmName("setBoardValue")
        set(value) {
        _builder.boardValue = value
      }
    /**
     * ```
     * string stm32_firmware_version = 2;  // DEPRECATED
     * ```
     *
     * `.focstim_rpc.BoardIdentifier board = 1;`
     */
    public fun clearBoard() {
      _builder.clearBoard()
    }

    /**
     * ```
     * FirmwareVersion esp32_firmware = ???;  // TODO: implement
     * ```
     *
     * `.focstim_rpc.FirmwareVersion stm32_firmware_version_2 = 3;`
     */
    public var stm32FirmwareVersion2: focstim_rpc.Messages.FirmwareVersion
      @kotlin.jvm.JvmName("getStm32FirmwareVersion2")
        get() = _builder.stm32FirmwareVersion2
      @kotlin.jvm.JvmName("setStm32FirmwareVersion2")
        set(value) {
        _builder.stm32FirmwareVersion2 = value
      }
    /**
     * ```
     * FirmwareVersion esp32_firmware = ???;  // TODO: implement
     * ```
     *
     * `.focstim_rpc.FirmwareVersion stm32_firmware_version_2 = 3;`
     */
    public fun clearStm32FirmwareVersion2() {
      _builder.clearStm32FirmwareVersion2()
    }
    /**
     * ```
     * FirmwareVersion esp32_firmware = ???;  // TODO: implement
     * ```
     *
     * `.focstim_rpc.FirmwareVersion stm32_firmware_version_2 = 3;`
     * @return Whether the stm32FirmwareVersion2 field is set.
     */
    public fun hasStm32FirmwareVersion2(): kotlin.Boolean {
      return _builder.hasStm32FirmwareVersion2()
    }

    public val ResponseFirmwareVersionKt.Dsl.stm32FirmwareVersion2OrNull: focstim_rpc.Messages.FirmwareVersion?
      get() = _builder.stm32FirmwareVersion2OrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseFirmwareVersion.copy(block: `focstim_rpc`.ResponseFirmwareVersionKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseFirmwareVersion =
  `focstim_rpc`.ResponseFirmwareVersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.Messages.ResponseFirmwareVersionOrBuilder.stm32FirmwareVersion2OrNull: focstim_rpc.Messages.FirmwareVersion?
  get() = if (hasStm32FirmwareVersion2()) getStm32FirmwareVersion2() else null

