// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializeresponseAxisMoveTo")
public inline fun responseAxisMoveTo(block: focstim_rpc.ResponseAxisMoveToKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseAxisMoveTo =
  focstim_rpc.ResponseAxisMoveToKt.Dsl._create(focstim_rpc.Messages.ResponseAxisMoveTo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.ResponseAxisMoveTo`
 */
public object ResponseAxisMoveToKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Messages.ResponseAxisMoveTo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Messages.ResponseAxisMoveTo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Messages.ResponseAxisMoveTo = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Messages.ResponseAxisMoveTo.copy(block: `focstim_rpc`.ResponseAxisMoveToKt.Dsl.() -> kotlin.Unit): focstim_rpc.Messages.ResponseAxisMoveTo =
  `focstim_rpc`.ResponseAxisMoveToKt.Dsl._create(this.toBuilder()).apply { block() }._build()

