// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: focstim_rpc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializerpcMessage")
public inline fun rpcMessage(block: focstim_rpc.RpcMessageKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.RpcMessage =
  focstim_rpc.RpcMessageKt.Dsl._create(focstim_rpc.FocstimRpc.RpcMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.RpcMessage`
 */
public object RpcMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.FocstimRpc.RpcMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.FocstimRpc.RpcMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.FocstimRpc.RpcMessage = _builder.build()

    /**
     * `.focstim_rpc.Request request = 2;`
     */
    public var request: focstim_rpc.FocstimRpc.Request
      @kotlin.jvm.JvmName("getRequest")
        get() = _builder.request
      @kotlin.jvm.JvmName("setRequest")
        set(value) {
        _builder.request = value
      }
    /**
     * `.focstim_rpc.Request request = 2;`
     */
    public fun clearRequest() {
      _builder.clearRequest()
    }
    /**
     * `.focstim_rpc.Request request = 2;`
     * @return Whether the request field is set.
     */
    public fun hasRequest(): kotlin.Boolean {
      return _builder.hasRequest()
    }

    /**
     * ```
     * Requests requests = 3;
     * ```
     *
     * `.focstim_rpc.Response response = 4;`
     */
    public var response: focstim_rpc.FocstimRpc.Response
      @kotlin.jvm.JvmName("getResponse")
        get() = _builder.response
      @kotlin.jvm.JvmName("setResponse")
        set(value) {
        _builder.response = value
      }
    /**
     * ```
     * Requests requests = 3;
     * ```
     *
     * `.focstim_rpc.Response response = 4;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * Requests requests = 3;
     * ```
     *
     * `.focstim_rpc.Response response = 4;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * `.focstim_rpc.Notification notification = 5;`
     */
    public var notification: focstim_rpc.FocstimRpc.Notification
      @kotlin.jvm.JvmName("getNotification")
        get() = _builder.notification
      @kotlin.jvm.JvmName("setNotification")
        set(value) {
        _builder.notification = value
      }
    /**
     * `.focstim_rpc.Notification notification = 5;`
     */
    public fun clearNotification() {
      _builder.clearNotification()
    }
    /**
     * `.focstim_rpc.Notification notification = 5;`
     * @return Whether the notification field is set.
     */
    public fun hasNotification(): kotlin.Boolean {
      return _builder.hasNotification()
    }
    public val messageCase: focstim_rpc.FocstimRpc.RpcMessage.MessageCase
    @kotlin.jvm.JvmName("getMessageCase")
      get() = _builder.getMessageCase()

    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.FocstimRpc.RpcMessage.copy(block: `focstim_rpc`.RpcMessageKt.Dsl.() -> kotlin.Unit): focstim_rpc.FocstimRpc.RpcMessage =
  `focstim_rpc`.RpcMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val focstim_rpc.FocstimRpc.RpcMessageOrBuilder.requestOrNull: focstim_rpc.FocstimRpc.Request?
  get() = if (hasRequest()) getRequest() else null

public val focstim_rpc.FocstimRpc.RpcMessageOrBuilder.responseOrNull: focstim_rpc.FocstimRpc.Response?
  get() = if (hasResponse()) getResponse() else null

public val focstim_rpc.FocstimRpc.RpcMessageOrBuilder.notificationOrNull: focstim_rpc.FocstimRpc.Notification?
  get() = if (hasNotification()) getNotification() else null

