// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializesystemStatsESC1")
public inline fun systemStatsESC1(block: focstim_rpc.SystemStatsESC1Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.SystemStatsESC1 =
  focstim_rpc.SystemStatsESC1Kt.Dsl._create(focstim_rpc.Notifications.SystemStatsESC1.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.SystemStatsESC1`
 */
public object SystemStatsESC1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.SystemStatsESC1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.SystemStatsESC1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.SystemStatsESC1 = _builder.build()

    /**
     * `float temp_stm32 = 1;`
     */
    public var tempStm32: kotlin.Float
      @kotlin.jvm.JvmName("getTempStm32")
        get() = _builder.tempStm32
      @kotlin.jvm.JvmName("setTempStm32")
        set(value) {
        _builder.tempStm32 = value
      }
    /**
     * `float temp_stm32 = 1;`
     */
    public fun clearTempStm32() {
      _builder.clearTempStm32()
    }

    /**
     * `float temp_board = 2;`
     */
    public var tempBoard: kotlin.Float
      @kotlin.jvm.JvmName("getTempBoard")
        get() = _builder.tempBoard
      @kotlin.jvm.JvmName("setTempBoard")
        set(value) {
        _builder.tempBoard = value
      }
    /**
     * `float temp_board = 2;`
     */
    public fun clearTempBoard() {
      _builder.clearTempBoard()
    }

    /**
     * `float v_bus = 3;`
     */
    public var vBus: kotlin.Float
      @kotlin.jvm.JvmName("getVBus")
        get() = _builder.vBus
      @kotlin.jvm.JvmName("setVBus")
        set(value) {
        _builder.vBus = value
      }
    /**
     * `float v_bus = 3;`
     */
    public fun clearVBus() {
      _builder.clearVBus()
    }

    /**
     * `float v_ref = 4;`
     */
    public var vRef: kotlin.Float
      @kotlin.jvm.JvmName("getVRef")
        get() = _builder.vRef
      @kotlin.jvm.JvmName("setVRef")
        set(value) {
        _builder.vRef = value
      }
    /**
     * `float v_ref = 4;`
     */
    public fun clearVRef() {
      _builder.clearVRef()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.SystemStatsESC1.copy(block: `focstim_rpc`.SystemStatsESC1Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.SystemStatsESC1 =
  `focstim_rpc`.SystemStatsESC1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

