// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notifications.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package focstim_rpc;

@kotlin.jvm.JvmName("-initializesystemStatsFocstimV3")
public inline fun systemStatsFocstimV3(block: focstim_rpc.SystemStatsFocstimV3Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.SystemStatsFocstimV3 =
  focstim_rpc.SystemStatsFocstimV3Kt.Dsl._create(focstim_rpc.Notifications.SystemStatsFocstimV3.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `focstim_rpc.SystemStatsFocstimV3`
 */
public object SystemStatsFocstimV3Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: focstim_rpc.Notifications.SystemStatsFocstimV3.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: focstim_rpc.Notifications.SystemStatsFocstimV3.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): focstim_rpc.Notifications.SystemStatsFocstimV3 = _builder.build()

    /**
     * `float temp_stm32 = 1;`
     */
    public var tempStm32: kotlin.Float
      @kotlin.jvm.JvmName("getTempStm32")
        get() = _builder.tempStm32
      @kotlin.jvm.JvmName("setTempStm32")
        set(value) {
        _builder.tempStm32 = value
      }
    /**
     * `float temp_stm32 = 1;`
     */
    public fun clearTempStm32() {
      _builder.clearTempStm32()
    }

    /**
     * `float v_sys_min = 2;`
     */
    public var vSysMin: kotlin.Float
      @kotlin.jvm.JvmName("getVSysMin")
        get() = _builder.vSysMin
      @kotlin.jvm.JvmName("setVSysMin")
        set(value) {
        _builder.vSysMin = value
      }
    /**
     * `float v_sys_min = 2;`
     */
    public fun clearVSysMin() {
      _builder.clearVSysMin()
    }

    /**
     * `float v_sys_max = 6;`
     */
    public var vSysMax: kotlin.Float
      @kotlin.jvm.JvmName("getVSysMax")
        get() = _builder.vSysMax
      @kotlin.jvm.JvmName("setVSysMax")
        set(value) {
        _builder.vSysMax = value
      }
    /**
     * `float v_sys_max = 6;`
     */
    public fun clearVSysMax() {
      _builder.clearVSysMax()
    }

    /**
     * `float v_ref = 3;`
     */
    public var vRef: kotlin.Float
      @kotlin.jvm.JvmName("getVRef")
        get() = _builder.vRef
      @kotlin.jvm.JvmName("setVRef")
        set(value) {
        _builder.vRef = value
      }
    /**
     * `float v_ref = 3;`
     */
    public fun clearVRef() {
      _builder.clearVRef()
    }

    /**
     * `float v_boost_min = 4;`
     */
    public var vBoostMin: kotlin.Float
      @kotlin.jvm.JvmName("getVBoostMin")
        get() = _builder.vBoostMin
      @kotlin.jvm.JvmName("setVBoostMin")
        set(value) {
        _builder.vBoostMin = value
      }
    /**
     * `float v_boost_min = 4;`
     */
    public fun clearVBoostMin() {
      _builder.clearVBoostMin()
    }

    /**
     * `float v_boost_max = 7;`
     */
    public var vBoostMax: kotlin.Float
      @kotlin.jvm.JvmName("getVBoostMax")
        get() = _builder.vBoostMax
      @kotlin.jvm.JvmName("setVBoostMax")
        set(value) {
        _builder.vBoostMax = value
      }
    /**
     * `float v_boost_max = 7;`
     */
    public fun clearVBoostMax() {
      _builder.clearVBoostMax()
    }

    /**
     * `float boost_duty_cycle = 5;`
     */
    public var boostDutyCycle: kotlin.Float
      @kotlin.jvm.JvmName("getBoostDutyCycle")
        get() = _builder.boostDutyCycle
      @kotlin.jvm.JvmName("setBoostDutyCycle")
        set(value) {
        _builder.boostDutyCycle = value
      }
    /**
     * `float boost_duty_cycle = 5;`
     */
    public fun clearBoostDutyCycle() {
      _builder.clearBoostDutyCycle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun focstim_rpc.Notifications.SystemStatsFocstimV3.copy(block: `focstim_rpc`.SystemStatsFocstimV3Kt.Dsl.() -> kotlin.Unit): focstim_rpc.Notifications.SystemStatsFocstimV3 =
  `focstim_rpc`.SystemStatsFocstimV3Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

